<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Close</name>
   <tag></tag>
   <elementGuidId>533876fc-43e9-484f-979e-711ef7465290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__button61-BDI-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//bdi[@id='__button61-BDI-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>bcead111-9472-4dd7-835e-5ea22fa67401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__button61-BDI-content</value>
      <webElementGuid>3f4edb7e-7b33-430c-8803-1d7b4d543419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>53e35fbc-983e-4065-8743-d1de1dd49ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>9c057053-270c-4e5f-a211-0a5d04042001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__button61-BDI-content&quot;)</value>
      <webElementGuid>22d52b4e-db2c-4ac2-8940-537ded5846bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//bdi[@id='__button61-BDI-content']</value>
      <webElementGuid>35d713e9-8183-42f2-b2b3-57a80ca1c638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__button61-content']/bdi</value>
      <webElementGuid>ff2bdb74-f82d-470a-b372-35b6645851ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Information'])[6]/following::bdi[1]</value>
      <webElementGuid>be6707bb-d14d-4ec8-9633-3bbcb16e74c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/following::bdi[1]</value>
      <webElementGuid>41a92b94-b531-4938-80fb-b06625700f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinne Tack'])[1]/preceding::bdi[1]</value>
      <webElementGuid>c8ad091b-6d00-4396-a597-c11fc0ac03be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>ab6e6515-40cd-4035-a162-8704a3146a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/footer/div/button/span/span/bdi</value>
      <webElementGuid>33952011-4251-44dd-9a97-b018b216118f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[@id = '__button61-BDI-content' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>60aeef0e-1669-43ba-afc9-53379c3fd7f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
