<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Married</name>
   <tag></tag>
   <elementGuidId>1ddbb494-093e-465c-9d17-7c9a90580961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__item67-__box3-popup-list-3-content > div.sapMSLIDiv > div.sapMSLITitleOnly</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__item67-__box3-popup-list-3-content']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__item67-__box3-popup-list-3-content&quot;] >> internal:text=&quot;Married&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3aaef208-616a-4f36-a796-ea6776d3dbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSLITitleOnly</value>
      <webElementGuid>2974e349-1900-4a88-9efc-b27ebf7116a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Married</value>
      <webElementGuid>5c0ae99c-405d-4219-a1ce-4955c9ab0eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item67-__box3-popup-list-3-content&quot;)/div[@class=&quot;sapMSLIDiv&quot;]/div[@class=&quot;sapMSLITitleOnly&quot;]</value>
      <webElementGuid>f4266216-0a20-4dc1-ab1d-ba60c118ed7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__item67-__box3-popup-list-3-content']/div/div</value>
      <webElementGuid>90258711-6904-4ebe-af7f-783aaed027f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal cohabitation'])[1]/following::div[3]</value>
      <webElementGuid>77f395e3-894b-4f61-a3c4-dfae6cb253fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Divorced'])[1]/following::div[6]</value>
      <webElementGuid>1531308a-c9a4-4271-b701-2049e771e8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Separated'])[1]/preceding::div[1]</value>
      <webElementGuid>3b8ee21e-a3b1-40b1-82ec-30fbfe6ba31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single'])[1]/preceding::div[4]</value>
      <webElementGuid>c4408584-3cff-4178-a1ac-53cf8490ccc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Married']/parent::*</value>
      <webElementGuid>442ea498-de64-4e7b-a377-8d69ef1fa093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/div</value>
      <webElementGuid>ab316132-530c-4b37-9d72-351fb3111528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Married' or . = 'Married')]</value>
      <webElementGuid>8ba58267-3be1-4244-9f6a-3b35e06faf35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
