<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Male</name>
   <tag></tag>
   <elementGuidId>4e151762-3c47-4af4-9ec0-0ccbb5cd9490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__item68-__box8-popup-list-1-content > div.sapMSLIDiv > div.sapMSLITitleOnly</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__item68-__box8-popup-list-1-content']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Male&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4d628d4-dd97-4528-bbbe-9b050f65a95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSLITitleOnly</value>
      <webElementGuid>d60a39e1-6057-4d03-bf92-53a61ce3fa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>65befbc1-18a8-40a2-a45c-16a065349b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item68-__box8-popup-list-1-content&quot;)/div[@class=&quot;sapMSLIDiv&quot;]/div[@class=&quot;sapMSLITitleOnly&quot;]</value>
      <webElementGuid>1cdecf3e-7561-4dfd-a308-5b1a07983780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__item68-__box8-popup-list-1-content']/div/div</value>
      <webElementGuid>35f153e8-e8e4-488a-a18d-3b5de13044f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::div[3]</value>
      <webElementGuid>f604ddfc-01e8-4487-90fc-cd353388b7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender Partner is required'])[1]/following::div[12]</value>
      <webElementGuid>f218c50e-019b-4bac-871c-f77970c9dada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinne Tack'])[1]/preceding::div[23]</value>
      <webElementGuid>68f1fa69-57d0-4672-979c-d2a866b3fa05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinne Tack'])[2]/preceding::div[24]</value>
      <webElementGuid>7f37db08-0e5d-478c-8c39-352fa91bcd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Male']/parent::*</value>
      <webElementGuid>628a6473-5f35-49f9-b78a-1ab29faa92e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/ul/li[2]/div/div/div</value>
      <webElementGuid>09b3d853-6ff1-48f5-9d79-3f6599b7cccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>5b857391-6a7c-4955-a89c-91167bfa7ad9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
