<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please fill in all Partner Info for mar_c1fa7a</name>
   <tag></tag>
   <elementGuidId>7875a4d4-efc9-4e3f-8f39-b7d1a5ece2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sapMSLIDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__item62-content']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;List Item . Personal Information . . Please fill in all Partner Info for marital status 'Married' or 'Legal Cohabitation' . Error&quot;i >> internal:text=&quot;Please fill in all Partner Info for marital status 'Married' or 'Legal Cohabitat&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9dd22080-af91-4cfd-b95e-19a33589bd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMSLIDescription</value>
      <webElementGuid>e1ccc8f3-e978-4bb2-a774-dd311adc3a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please fill in all Partner Info for marital status 'Married' or 'Legal Cohabitation'</value>
      <webElementGuid>65e0dfdb-42c5-4437-b76f-8c9024fe949e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__item62-content&quot;)/div[@class=&quot;sapMSLIDiv&quot;]/div[@class=&quot;sapMSLIDescription&quot;]</value>
      <webElementGuid>48e2dd7a-daf5-4500-be88-a20c572431a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__item62-content']/div/div[2]</value>
      <webElementGuid>c9f1cda7-7951-4b0f-823d-74c388444913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Information'])[6]/following::div[4]</value>
      <webElementGuid>261ecd72-d958-4942-81ee-7baa90342da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/following::div[14]</value>
      <webElementGuid>e3ee60cf-f483-40bc-8f06-79ca32e28043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[3]</value>
      <webElementGuid>d3eebf75-131c-4d7f-90e0-9ef5e72476b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinne Tack'])[1]/preceding::div[25]</value>
      <webElementGuid>cd1516e9-6863-4782-b8aa-29ca420caeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]</value>
      <webElementGuid>562e4750-08cf-476c-9132-c635e5219103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Please fill in all Partner Info for marital status &quot; , &quot;'&quot; , &quot;Married&quot; , &quot;'&quot; , &quot; or &quot; , &quot;'&quot; , &quot;Legal Cohabitation&quot; , &quot;'&quot;) or . = concat(&quot;Please fill in all Partner Info for marital status &quot; , &quot;'&quot; , &quot;Married&quot; , &quot;'&quot; , &quot; or &quot; , &quot;'&quot; , &quot;Legal Cohabitation&quot; , &quot;'&quot;))]</value>
      <webElementGuid>e6f90f19-f8d9-4af3-be92-827308bcfcf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
