<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Formal Name___input3-inner</name>
   <tag></tag>
   <elementGuidId>1c2654b9-5aa9-47eb-9c19-f709edf6d659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__input3-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__input3-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Formal Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13e61fde-da28-4603-bdee-374f0d6f9952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__input3-inner</value>
      <webElementGuid>df51d82b-29fa-402e-84a9-8b668f5f254e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>4139470c-5af9-43d9-9a45-18a238e15149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tinne Tack</value>
      <webElementGuid>c1aed307-6f23-48d7-b72b-7c6bcf43136e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__label39</value>
      <webElementGuid>3cbbf094-c1f0-455e-9073-46a8d3b50cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-moz-errormessage</name>
      <type>Main</type>
      <value>Tinne Tack</value>
      <webElementGuid>06b9c909-131f-42ab-bff6-158c248af5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>659b69e8-2a03-4c51-965a-7448331b3999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cf04ca07-aab8-4dda-a9bc-a299690c9b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMInputBaseInner</value>
      <webElementGuid>66458da9-20c5-447d-8493-030943e6de60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__input3-inner&quot;)</value>
      <webElementGuid>a434359f-85b3-442c-b911-7c16852504ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__input3-inner']</value>
      <webElementGuid>2f367c1f-e8c9-4f3d-abb3-39ed7219d4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__input3-content']/input</value>
      <webElementGuid>cbb55d98-5823-4545-82e6-e4512c6cc62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>a6358c3d-fbec-4506-8d81-41b8f3dbede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '__input3-inner' and @type = 'text']</value>
      <webElementGuid>e078b5a5-5784-4561-bcb1-c62b54682ae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
