<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_19</name>
   <tag></tag>
   <elementGuidId>685011d0-24bb-44e2-b77c-0587f175d8d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__picker3-cal--Month0-20250219 > span.sapUiCalItemText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__picker3-cal--Month0-20250219']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;19&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f1e6a2c-38da-4fe1-8696-0c116e8f328c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiCalItemText</value>
      <webElementGuid>ebbe33d1-83b0-4c21-844b-453b7c7f8ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>51b072d6-0315-45f7-acbc-c04ed6708dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__picker3-cal--Month0-20250219&quot;)/span[@class=&quot;sapUiCalItemText&quot;]</value>
      <webElementGuid>91f12ba9-3eae-4553-8f8f-26d121ea2d95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__picker3-cal--Month0-20250219']/span</value>
      <webElementGuid>bd02fe1b-db44-47f9-9fc2-f3e22671398b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/following::span[24]</value>
      <webElementGuid>587f532a-e600-4956-ab59-df1e426dfe68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[24]</value>
      <webElementGuid>b8654c09-05ce-493f-ba65-0be545311f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinne Tack'])[1]/preceding::span[29]</value>
      <webElementGuid>71f2b3b8-d9d6-430a-9ff1-cd50f2f8ce5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinne Tack'])[2]/preceding::span[30]</value>
      <webElementGuid>80f4d1a0-ae0d-4688-9ced-d982b1087ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19']/parent::*</value>
      <webElementGuid>1b2a14ed-0a39-46d2-8f17-6defeeb37a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/span</value>
      <webElementGuid>4bdc9c4b-64b5-4e5b-aafc-64ff5f3debc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '19' or . = '19')]</value>
      <webElementGuid>4e36bc84-54fb-4dcf-b28a-1a423855db1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
