<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_19</name>
   <tag></tag>
   <elementGuidId>4b3ccab1-9488-4b1f-939a-eba2a0c0b775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__picker3-cal--Month0-20250219 > span.sapUiCalItemText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__picker3-cal--Month0-20250219']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;19&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>143106a8-bee2-4ecd-a1bf-1914c97d707e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiCalItemText</value>
      <webElementGuid>d19b7c52-1c91-433b-9017-73854a9b7d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>5176d09d-a6ef-443a-9f4e-b87b9587df04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__picker3-cal--Month0-20250219&quot;)/span[@class=&quot;sapUiCalItemText&quot;]</value>
      <webElementGuid>89b1715c-ebfb-4a5c-9f0e-1f9d671b51e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__picker3-cal--Month0-20250219']/span</value>
      <webElementGuid>9599adba-0239-4d96-866d-c2c64af7711a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/following::span[24]</value>
      <webElementGuid>3cee8957-724a-450b-ab21-178f3cc543e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[24]</value>
      <webElementGuid>aa694024-fb52-4484-ac4f-561b8b28da49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinne Tack'])[1]/preceding::span[29]</value>
      <webElementGuid>62b7ea7f-398f-4511-a687-d598c69316c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinne Tack'])[2]/preceding::span[30]</value>
      <webElementGuid>a9341c82-1e4a-471b-8499-ec36b9958cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19']/parent::*</value>
      <webElementGuid>3f0be7c0-417e-4d9a-85cb-5a64e8cd6698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/span</value>
      <webElementGuid>4f4eeea7-d0b2-4647-8908-a090f0d46d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '19' or . = '19')]</value>
      <webElementGuid>c6c4004b-860c-4f53-adb2-03c3d357dfaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
