<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Close_1</name>
   <tag></tag>
   <elementGuidId>35562829-629c-4d0b-8af9-e811d88aa52e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__mbox-btn-0-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__mbox-btn-0-inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>94aaca15-103d-41e2-a964-1c9b993c4864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__mbox-btn-0-inner</value>
      <webElementGuid>d39286fb-dc41-4b9b-b7ef-d355e5ce32e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnInner sapMBtnHoverable sapMFocusable sapMBtnText sapMBtnDefault</value>
      <webElementGuid>2a409214-de5f-498b-88fb-98b349304b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>0999cc4d-0d9a-4ecd-8f47-d8415769d50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__mbox-btn-0-inner&quot;)</value>
      <webElementGuid>5c5dfe8e-8292-4a28-bd9f-682a03cda5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__mbox-btn-0-inner']</value>
      <webElementGuid>5a7d3493-fe05-411c-95b1-7b58b2f85a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='__mbox-btn-0']/span</value>
      <webElementGuid>fc7109ec-cd4c-4b60-989b-00c042970f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender Partner is required'])[1]/following::span[1]</value>
      <webElementGuid>8cf6e98c-7554-42a1-81c1-49054f996551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::span[7]</value>
      <webElementGuid>7b37ae3e-f21b-441c-9a58-864124d628b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/footer/div/button/span</value>
      <webElementGuid>206b9603-3b70-40f6-8417-bdba53ed71b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__mbox-btn-0-inner' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>dfef62e9-0d0a-45d9-8ac8-166302a081b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
