<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Personal Information___button47-img</name>
   <tag></tag>
   <elementGuidId>80548be7-3fdf-45f0-9817-0fe8e6709cbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__button47-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div/div/section/div/div[2]/section/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[1]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[1]/div/span/div/button[1]/span[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Edit Personal Information&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f99241e4-b14d-4f43-a433-67a3aed3845b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__button47-img</value>
      <webElementGuid>429b781d-ad43-4709-a53a-0ada2cfed282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__button47-img</value>
      <webElementGuid>d8351f05-bef4-4148-86db-a7724dff8553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>578a7b4a-a3f0-4af8-a048-36d9b109c7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a15ece15-add8-47ee-9e81-bd733fdb0e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fed08f2c-3a7b-4273-95b2-e7830a0cdc91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapMBtnCustomIcon sapMBtnIcon sapMBtnIconLeft</value>
      <webElementGuid>64c8b8f4-1faa-4d02-bee8-28cb1e763ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__button47-img&quot;)</value>
      <webElementGuid>b614b1de-9ba3-488d-ac5e-911e4e65cc59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__button47-img']</value>
      <webElementGuid>ccb8574a-2205-4a71-ba74-bd2de92ffa95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__button47-inner']/span</value>
      <webElementGuid>46a2ab0e-d9e3-4cba-b213-bcdf9c2d6c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div/span/div/button/span/span</value>
      <webElementGuid>fb5ec891-8670-4e23-9665-276724e2c1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__button47-img']</value>
      <webElementGuid>72b4b03b-56b4-4c20-b8fa-823650c2c124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
