<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_When should these changes take effect__d54225</name>
   <tag></tag>
   <elementGuidId>e3362756-16c4-493e-855f-7a3f8580853a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__picker3-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__picker3-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open Picker&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aca9b50f-2a87-44df-8cfd-339d8a2a1e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__picker3-icon</value>
      <webElementGuid>0676c578-bba9-43c1-ade2-2835b7bfe1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui</name>
      <type>Main</type>
      <value>__picker3-icon</value>
      <webElementGuid>cfe72765-443a-40f7-a9fa-ec6ec2252a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c0df0ac7-b10b-4ada-a69a-fdfc38c3862f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7514c8a3-cb7b-4082-a4cf-9c2926307d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open Picker</value>
      <webElementGuid>a73989d3-613d-433b-9de2-9e59d19d7bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-icon-content</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a12a991e-a5e3-423f-a1d6-f17aceca5737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiIcon sapUiIconMirrorInRTL sapUiIconPointer sapMInputBaseIcon</value>
      <webElementGuid>d1cc60ce-6a53-4885-a037-d3d972410262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__picker3-icon&quot;)</value>
      <webElementGuid>dd7a8f05-6b5d-4d33-ae49-496781b6ba9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__picker3-icon']</value>
      <webElementGuid>59731229-6cb0-47f2-ad04-2f61ebc2bc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__picker3-content']/div/span</value>
      <webElementGuid>bc53e8ad-9c7d-4eb4-890b-aa7d3a97c5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
      <webElementGuid>4ed3ba9c-54be-4d14-8edc-326e20ea691f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__picker3-icon']</value>
      <webElementGuid>d627d567-9f5e-44fb-bca8-d6136e129dcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
