<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Close</name>
   <tag></tag>
   <elementGuidId>8bb8f580-5db0-47c2-aee6-7b9c399d4093</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__button67-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='__button67-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>07070abb-fc1c-4365-98c4-e11820753955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__button67-content</value>
      <webElementGuid>dbca5cc7-41f9-41e7-95b6-01d28c63e39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapMBtnContent</value>
      <webElementGuid>8f0e871d-7b42-40c1-a980-c5033cd23fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>1333885c-2c48-4ae3-a6ab-baf5ab99e902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__button67-content&quot;)</value>
      <webElementGuid>a2e742f1-5e93-4db2-b7dd-ba49b16751bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='__button67-content']</value>
      <webElementGuid>5a55d575-d1f1-48fb-8da6-aaba8897adb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='__button67-inner']/span</value>
      <webElementGuid>5a5d3798-c27c-4a94-8125-022ca71b2d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Information'])[7]/following::span[7]</value>
      <webElementGuid>4fae08d7-8e47-4dd1-a10a-2ce4dd46a3c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/following::span[9]</value>
      <webElementGuid>21d82d41-0c07-465a-8bd9-7a3552f3893b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/footer/div/button/span/span</value>
      <webElementGuid>4df6cd23-764e-4d1d-b55e-5bcb7b121745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '__button67-content' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>fb99494c-8ba2-43dd-b718-4aa8c80209a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
