<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_About this page_a-uhkwfxak3vce</name>
   <tag></tag>
   <elementGuidId>ee0d19be-e476-422c-bda4-6ecc490f789e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-uhkwfxak3vce&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-uhkwfxak3vce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-uhkwfxak3vce&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>49450721-1077-4731-8246-709d9de3fd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>733ecfaa-7bff-4ca6-8212-e2d5f37941fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>717ca8e8-cd12-4971-a03e-1e54cf13e9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>d6b57a7e-b84f-44a0-8e7b-ecb41ad6887c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c9c400fb-4164-4f93-ae28-4b87c910b1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-uhkwfxak3vce</value>
      <webElementGuid>25bcf767-010c-48e9-9b5c-e6915c7a7563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16f8305d-512f-401a-ad13-5ac25ac8f6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c252a50d-6732-4f0e-85fa-8c129113945f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>10301234-3be5-4f9c-8c2e-bce36c4b3684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;size=normal&amp;s=-kCZZhp2UcnoLOPuLDs6oqx4TTSigHlq4Ic3LyhdU7E4h2qHPtsXsKwni5NDbeaGooQ1oA2hbWOts4Y7CDTUlWPJYfCKg-Mywzp9EHEASxrCbauqI2sN3-5Yvh95BxfICiVlVYcOZuMGepV4HmnzN_SFb2Qeax9_aLdbvRocIrH4LdFZkbdDZKDfXQcRNymXZNA59Q8ovFz-W-gwlIiQwENbJhbsux_gZQlL_8U5gV--ZkZCpU6m7bGdWK135QijqAo8e8D1fQix6Z5sQ6T3x4DuwGFVttQ&amp;cb=yk4guq6l7st3</value>
      <webElementGuid>93705380-b24e-43e0-89dd-30d0c5ac3dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>403a8146-6d3d-49f4-a1e3-6df5b89ce2c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-uhkwfxak3vce']</value>
      <webElementGuid>efac1290-d422-4376-a11e-18c5c0c92bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha']/div/div/iframe</value>
      <webElementGuid>b8f3389f-fc35-44e4-8e96-eda8ab10c127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4907e6f1-21ac-44ae-824c-57c779aceeff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-uhkwfxak3vce' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;size=normal&amp;s=-kCZZhp2UcnoLOPuLDs6oqx4TTSigHlq4Ic3LyhdU7E4h2qHPtsXsKwni5NDbeaGooQ1oA2hbWOts4Y7CDTUlWPJYfCKg-Mywzp9EHEASxrCbauqI2sN3-5Yvh95BxfICiVlVYcOZuMGepV4HmnzN_SFb2Qeax9_aLdbvRocIrH4LdFZkbdDZKDfXQcRNymXZNA59Q8ovFz-W-gwlIiQwENbJhbsux_gZQlL_8U5gV--ZkZCpU6m7bGdWK135QijqAo8e8D1fQix6Z5sQ6T3x4DuwGFVttQ&amp;cb=yk4guq6l7st3']</value>
      <webElementGuid>146b4716-e3ee-441b-8f73-832facdfe42c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
