<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3</name>
   <tag></tag>
   <elementGuidId>2d45527b-eb22-438b-b91c-69f9e2e2770d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bacaab11-8c4f-4b27-a6c1-4ad94f524bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>41704fc6-7d3d-4657-aca1-0eccff11df57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>2c7d1c0e-0cc9-444f-9a73-e4d822b3a61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>c8299b82-45d0-4e19-bed2-a83656e4ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqplopsalandsc_f53a5e/iframe_html1body1div2div4iframe1_c-uhkwfxak3vce</value>
      <webElementGuid>b898453a-8730-402f-bc01-ba4a0a69b6e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>ffa97cb9-e404-4fe0-b9a0-f2821927ba27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[8]</value>
      <webElementGuid>8fad72eb-8ac9-4bc2-9389-c8b206442289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>251dd409-dc17-48aa-85aa-a8997e839232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>c0f263eb-fbb0-402d-b9aa-fe6556c767a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
