<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1_2</name>
   <tag></tag>
   <elementGuidId>3f4c467f-6d1d-4cd2-87a9-7705d781bc65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8dfc331b-bb5c-4edc-b6c0-4f4e6c6a69a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>5475bc63-5c55-431d-82f7-29364ed5f5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6q5RX5vwH096qaYxq3wYs2hd-MxdeXuwoiPpcap7m1996xTOano9zqzTC6Hc_28pw0jPvNHH4dDD0ocNslbIE7OoVzSFo2WF01dXoQN9zoZR00LLhmygcXH0RWbdFUpSEdphjmvmxVSnsEqQxU-vFDUddQRED43FyFNAroC2xM-gd20ZgZQlpajIgAOUH8XNlI6FoR8_5V__B1Kx8ZhB6inr82B0Eq5KyLQ1gmAeL97EIq5Mg&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>431e5204-e40a-457a-ac81-02dee3dd9cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>3121d736-52ef-448d-90f7-2f860812eb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqplopsalandsc_f53a5e/iframe_html1body1div2div4iframe1_c-uhkwfxak3vce</value>
      <webElementGuid>a842f66b-9f6d-4bc3-82f6-a1b4b3e74feb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>7d4df66c-e16a-4fc4-9707-332c95f282e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6q5RX5vwH096qaYxq3wYs2hd-MxdeXuwoiPpcap7m1996xTOano9zqzTC6Hc_28pw0jPvNHH4dDD0ocNslbIE7OoVzSFo2WF01dXoQN9zoZR00LLhmygcXH0RWbdFUpSEdphjmvmxVSnsEqQxU-vFDUddQRED43FyFNAroC2xM-gd20ZgZQlpajIgAOUH8XNlI6FoR8_5V__B1Kx8ZhB6inr82B0Eq5KyLQ1gmAeL97EIq5Mg&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')]</value>
      <webElementGuid>c6237fcb-0424-466a-b075-1c86154a0d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>38a09f37-811f-429d-a631-6c6cefa11559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6q5RX5vwH096qaYxq3wYs2hd-MxdeXuwoiPpcap7m1996xTOano9zqzTC6Hc_28pw0jPvNHH4dDD0ocNslbIE7OoVzSFo2WF01dXoQN9zoZR00LLhmygcXH0RWbdFUpSEdphjmvmxVSnsEqQxU-vFDUddQRED43FyFNAroC2xM-gd20ZgZQlpajIgAOUH8XNlI6FoR8_5V__B1Kx8ZhB6inr82B0Eq5KyLQ1gmAeL97EIq5Mg&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>46862a7d-f960-423f-9a2d-0600c789eb53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
