<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1_2_3</name>
   <tag></tag>
   <elementGuidId>62916302-52ea-4916-8a1d-2a106c9ebfe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>01ee10a9-b69b-42db-8c41-20138c5aeba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>c28bc0d0-1834-4c5f-9379-6b9c1ef62d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6q5RX5vwH096qaYxq3wYs2hd-MxdeXuwoiPpcap7m1996xTOano9zqzTC6Hc_28pw0jPvNHH4dDD0ocNslbIE7OoVzSFo2WF01dXoQN9zoZR00LLhmygcXH0RWbdFUpSEdphjmvmxVSnsEqQxU-vFDUddQRED43FyFNAroC2xM-gd20ZgZQlpajIgAOUH8XNlI6FoR8_5V__B1Kx8ZhB6inr82B0Eq5KyLQ1gmAeL97EIq5Mg&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>0fcd3aba-3fc9-4e78-a3bc-e790cb2fa02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>79c681de-ea76-4c33-bedd-e5a43763d514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqplopsalandsc_f53a5e/iframe_html1body1div2div4iframe1_c-uhkwfxak3vce</value>
      <webElementGuid>5e871ce1-677f-45a6-9820-db17b9fdaeb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>fc252cac-b44a-4445-9f69-6be69f0625d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6q5RX5vwH096qaYxq3wYs2hd-MxdeXuwoiPpcap7m1996xTOano9zqzTC6Hc_28pw0jPvNHH4dDD0ocNslbIE7OoVzSFo2WF01dXoQN9zoZR00LLhmygcXH0RWbdFUpSEdphjmvmxVSnsEqQxU-vFDUddQRED43FyFNAroC2xM-gd20ZgZQlpajIgAOUH8XNlI6FoR8_5V__B1Kx8ZhB6inr82B0Eq5KyLQ1gmAeL97EIq5Mg&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[7]</value>
      <webElementGuid>6f2eeba1-bfe9-445c-a175-13384790afe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>d5cb3aca-15af-462d-b820-74de206dcb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6q5RX5vwH096qaYxq3wYs2hd-MxdeXuwoiPpcap7m1996xTOano9zqzTC6Hc_28pw0jPvNHH4dDD0ocNslbIE7OoVzSFo2WF01dXoQN9zoZR00LLhmygcXH0RWbdFUpSEdphjmvmxVSnsEqQxU-vFDUddQRED43FyFNAroC2xM-gd20ZgZQlpajIgAOUH8XNlI6FoR8_5V__B1Kx8ZhB6inr82B0Eq5KyLQ1gmAeL97EIq5Mg&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>6c8edf6e-e239-4576-8ab0-9e221b734ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
