<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1</name>
   <tag></tag>
   <elementGuidId>28ac83cd-1814-45b1-b61f-6b8110e0eb8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>230c2c43-72b9-4f75-aa49-b80a5aa64efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>22c29845-aafa-415f-a2ce-504cf67b3ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>81707fb5-fb85-49b2-8e42-180b0586daee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>d98a33dc-471c-4828-8f92-1894198e24fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqplopsalandsc_f53a5e/iframe_html1body1div2div4iframe1_c-uhkwfxak3vce</value>
      <webElementGuid>a4b01bb4-27ef-4ffb-8428-cfae0a71711b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>0e6c0621-3efa-4eac-a862-91602b45c1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[9]</value>
      <webElementGuid>a846a625-d5e2-47e4-a7ed-0c01dd592fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>952ed99d-e3e1-4f0f-8c84-1031d33e61e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>9202a101-f5ca-4fb6-bfe6-2c61ff470034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
