<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>69ce0e5c-59c5-40f1-bf1e-1f6722be7c92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>880a5705-0608-4d7a-ac82-d62a8510c6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>2571c4cb-5479-4c3d-8f1b-da2b658780b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>91ca9653-0f0d-446c-b294-2e2bcb3ead86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>851c96ca-a282-4160-ab7d-f411f37631fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqplopsalandsc_f53a5e/iframe_html1body1div2div4iframe1_c-uhkwfxak3vce</value>
      <webElementGuid>ce99a8f0-893b-4e68-8ecf-50d9eeb30871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>88f78640-4857-4c9d-ac0f-ff53bae686b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[3]</value>
      <webElementGuid>ab57a41b-c8d5-4736-a274-37fcf56bb8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>f587f779-fb34-435d-85d0-1b41977f6a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA41LLtqOYrj3R9cGibxV6-bDMRvDRiwFKxgjPGkwBeD46bHD2LNvjnITSEzMw555Vyw2SXs-RKVhckgKz1Tkfi6vt1bIDlyDVUPq6VNsOJzwwZVUTARW_UZGiHexi-n_6EXGhBkSNTfzA0TPKs-puRCEbakG3y3E5be0cLvbXQHygOUBL0GeLgMQNsJz3lz6jxnTD41-MrlK16eGSN3CSwoIwASPNKP2I50khfl9NDb94X5O6A&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>af46ef9b-4fd2-42b6-a4f1-de17c78a8b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
