# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: katalonTask@1
  inputs:
    version: '10.1.0'
    location: katalonc -noSplash -runMode=console -projectPath="C:\Users\hostej\Katalon Studio\Katalon - Julie Test Case\Katalon - Julie Test Case.prj" -retry=0 -testSuitePath="Test Suites/TS - Alerts" -browserType="Chrome" -executionProfile="default" -apiKey="a0d2a3a7-65e3-48a5-bfb3-b6017f8055cb" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true