<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1</name>
   <tag></tag>
   <elementGuidId>6d178103-839e-4410-9d3f-ef4cdc6ad7d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>301f4c48-270e-4be2-9480-2400d858e2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>65882d14-6c26-465a-845d-970248c22db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>235f69b1-3e56-4696-8089-9fb8c9dcfc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>5178e15e-6a6a-46e7-a167-150b203f1ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqKatalonsca_e_c86a67/iframe_html1body1div2div4iframe1_c-g3u0md3g3708</value>
      <webElementGuid>d416a5a6-844c-45b7-b227-d1feabd8d04e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>4b27dae0-bae7-4f3a-81e4-3c372546909a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')]</value>
      <webElementGuid>ac9b7c4c-706e-4985-aee7-61188151e0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3314d51f-d2c9-4352-9b1c-8920fa587a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>1557063d-201d-4cae-9d72-85a4a88161d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
