<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3</name>
   <tag></tag>
   <elementGuidId>43b8efc8-c8e4-477f-bde4-9e104d2e9109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>339d63b4-991f-4ed9-a695-b005446ed5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>c6db84fb-f431-477a-9fed-6ba21edd13c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>145f730a-1984-4ef2-8ac9-17181b5187e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>64893ffa-4e1b-4286-8699-23146ddbbe32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqKatalonsca_e_c86a67/iframe_html1body1div2div4iframe1_c-g3u0md3g3708</value>
      <webElementGuid>cd19ad19-81a4-44c6-8626-f0d14719aba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      <webElementGuid>4a47a568-d8b8-4847-8bc6-399b0fde3269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[4]</value>
      <webElementGuid>f20416df-ca31-4433-a96b-5ccb900bf1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>76cedcc8-e3bf-4c15-880e-74d390eab499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>93721e77-25a5-4516-ae44-8f84418a33dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
