<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>2e3895f7-f66b-413a-8573-823b102f6f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2b1ca28f-832b-4065-ae3a-68c4daf007b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>211fe234-6ebf-4ca3-bcfd-f07ee9681b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>e08ecfbe-d6c6-46a0-8804-f395854936a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>8d922f7a-f432-4e86-a4cf-df03a77f7750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqKatalonsca_e_c86a67/iframe_html1body1div2div4iframe1_c-g3u0md3g3708</value>
      <webElementGuid>8654f383-8c35-4c40-9aea-79f143b257a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>bdbfe17b-a3a5-40fc-af8d-08e629be8b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[9]</value>
      <webElementGuid>44aaff50-5a3c-4dd5-9819-bcef4f0a84fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>469f958f-3bf2-4b14-af50-cef61262a560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4GMa0NuDSfo-QUmVh0hFmg52W9livhvjfZIKRuZ19GgLBdNVm_mg1Y1lPXLRafkRxoysmh4i9Oq2RKTNScBZegZ2YAGP38BKD2RBXBT4hU7RtWvDKQbuLfK4us9sM7BNhMig3u4ubi4Vdtz4c79cCz3ZR_h9gi6dtEwC2IQgMNeOKPgR7hXe23IO8ml_iqg7KaL3YrRuJPth9_RTR1jCTFBQ76O3uyDfLiRjOY5xP8Qlhl5ig&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>20d9a75f-e5f1-4376-b9af-ef3c16588caa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
