<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log On</name>
   <tag></tag>
   <elementGuidId>dccc23ed-3ce3-4ea2-bdd8-286805d5b17c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nsg-x1-logon-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nsg-x1-logon-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Log On&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d619961-9425-4726-93f0-36d7dcaba0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nsg-x1-logon-button</value>
      <webElementGuid>c734f52a-51bc-4c90-982b-a2a98069fa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2b9b8d2b-d785-43e4-bd7b-726c21807bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button forms-authentication-button last-child default</value>
      <webElementGuid>c52c56ce-c49d-461a-8aee-04032fed3737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log On</value>
      <webElementGuid>8a154e6c-3a26-4582-83c0-ddcae37244ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nsg-x1-logon-button&quot;)</value>
      <webElementGuid>151e0bad-f30d-4a1e-bfba-28f0dc0ca7ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nsg-x1-logon-button']</value>
      <webElementGuid>6ebffa5d-8c14-430d-b468-7d2035ef27c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='explicit-auth-screen']/div[3]/div/div[2]/div[2]/div[3]/div/form/div[5]/div/a</value>
      <webElementGuid>02c88b8a-9a1f-46ea-91cf-9351d460a3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log On')]</value>
      <webElementGuid>42bf0ae8-3c7f-4f90-9901-031eedb38657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember my credentials'])[1]/following::a[1]</value>
      <webElementGuid>c8aeeb43-dee0-49b0-ab75-7a134321c296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password :'])[1]/following::a[1]</value>
      <webElementGuid>46770860-8c22-49fe-aae8-fa2b4e3a48eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resuming logon, please wait.'])[1]/preceding::a[1]</value>
      <webElementGuid>e607af2e-e902-4e64-9277-58f29c3a8dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to change your password?'])[1]/preceding::a[2]</value>
      <webElementGuid>893d2d44-b25f-4992-9f30-e38249c50e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log On']/parent::*</value>
      <webElementGuid>82e4a239-c748-41f3-973d-8832fa35c6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[40]</value>
      <webElementGuid>ec78fc48-644a-4b4a-a9d6-4c995b5a974c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>451ebe28-9f76-4a54-9b94-be9fbcb4514f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nsg-x1-logon-button' and @href = '#' and (text() = 'Log On' or . = 'Log On')]</value>
      <webElementGuid>a4041644-57e7-4f94-bda7-7fc9ebace344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
