<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputui5wc_19-inner-d9b-ec5-604</name>
   <tag></tag>
   <elementGuidId>62b89749-1481-4a79-9083-aa4f0bea5d0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui5-input-root.ui5-input-focusable-element > div.ui5-input-content > #ui5wc_19-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'ui5wc_19-inner' and @type = 'text' and @placeholder = 'Search for actions or people']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7599e0c3-23c9-40c1-9e4c-1e13eadae8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui5-input-inner</value>
      <webElementGuid>5ab31e31-cd00-4d19-aed9-7514b945745e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fb05ce69-bff7-41f9-a15a-6bbe47887207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui5wc_19-inner</value>
      <webElementGuid>388414cb-f06f-425b-b182-e60ed532446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c5d4fbf-9d11-42ee-8eb0-9c2fd8ab9ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for actions or people</value>
      <webElementGuid>eeb76236-f02a-475a-a944-18fd381510e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>094710c4-3f06-4b82-9103-bf32ea01abca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ui5wc_19-suggestionsText</value>
      <webElementGuid>de852321-ee41-4f41-9c1a-575335b6911e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>717e2920-bb3d-4306-a588-30310c30a5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.</value>
      <webElementGuid>99652194-0613-4bb3-939f-433c3ca13af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9ad3a485-2de5-4500-8b96-66b097732203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e0b8550-7ba2-40f6-90c3-3d8d2ae534e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;ui5-input-root ui5-input-focusable-element&quot;]/div[@class=&quot;ui5-input-content&quot;]/input[@id=&quot;ui5wc_19-inner&quot;]</value>
      <webElementGuid>5d05177a-6d6f-4f3b-89b0-9c4c0d5d3fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2956b6e1-f834-447f-b985-824fe187d7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/xweb-shellbar-search-input_1 TackSearch Tin_baef7b</value>
      <webElementGuid>e8c3a373-5b94-4d2b-9c88-e0672d6413a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ui5wc_19-inner' and @type = 'text' and @placeholder = 'Search for actions or people']</value>
      <webElementGuid>b9c8a943-5f42-460d-ba0a-fd63512113d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
