<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputui5wc_19-inner-d9b-ba8-4a1</name>
   <tag></tag>
   <elementGuidId>34fa7fc6-65ec-461b-ae50-e1c4bdfdc39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui5-input-root.ui5-input-focusable-element > div.ui5-input-content > #ui5wc_19-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'ui5wc_19-inner' and @type = 'text' and @placeholder = 'Search for actions or people']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35900f39-cbbd-44ed-9638-285be33244d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui5-input-inner</value>
      <webElementGuid>47ec62fa-e228-49da-b21e-874daab1f6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d807e773-1d7f-4449-aafc-60a5b3670ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui5wc_19-inner</value>
      <webElementGuid>711fe731-85f0-4fdb-8bc0-72776071ef3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6df15b08-1819-4b5c-8f54-68979a3f5f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for actions or people</value>
      <webElementGuid>48ed2896-c408-4671-af1e-d8170d744538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d0ff49ca-87b4-409f-8fce-b050494e3614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ui5wc_19-suggestionsText</value>
      <webElementGuid>2ab158ad-5c1a-4241-9908-4b840378ed8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>a2fbfc8e-7785-454b-875c-03fc20123b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.</value>
      <webElementGuid>1399c827-d979-45bd-9744-ca5ecd0a6c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff617493-6d44-4942-8638-786cb6ede6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>968343ab-7012-4a9f-ab22-321b5269e617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;ui5-input-root ui5-input-focusable-element&quot;]/div[@class=&quot;ui5-input-content&quot;]/input[@id=&quot;ui5wc_19-inner&quot;]</value>
      <webElementGuid>186b2ec6-9df7-4476-9669-493b8143a568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db5155e5-38ec-4d97-8a91-3178356d231b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/xweb-shellbar-search-input_Tinne TackSearch_695e91</value>
      <webElementGuid>fba28771-0f5a-474c-8995-1259eb7bd203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ui5wc_19-inner' and @type = 'text' and @placeholder = 'Search for actions or people']</value>
      <webElementGuid>8f0d06b1-3e15-4edc-8f30-369dcbdd78f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
