<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputui5wc_19-inner-d9b-f9d-70e</name>
   <tag></tag>
   <elementGuidId>100b29c5-18bd-4704-8ab6-5faf374b62ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui5-input-root.ui5-input-focusable-element > div.ui5-input-content > #ui5wc_19-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'ui5wc_19-inner' and @type = 'text' and @placeholder = 'Search for actions or people']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9259a34-bae4-42dc-8e9f-aa802097dd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui5-input-inner</value>
      <webElementGuid>503601f6-5520-43dd-9bbb-291db174d822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c97fb140-3375-471d-ac9a-bc7429dc5cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui5wc_19-inner</value>
      <webElementGuid>09127219-5ca1-4c18-be2b-645e3e50061b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>472d9737-6ba0-428b-9668-b7c765ddeb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for actions or people</value>
      <webElementGuid>6fed7e0f-59d9-4260-bc42-8cdfb0e2f7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2511f9ae-db19-4d2d-a0cb-e08f9b695cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ui5wc_19-suggestionsText ui5wc_19-valueStateDesc</value>
      <webElementGuid>d580e88b-6837-427c-bc32-8dbd3314fdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>299d78bc-cfa5-4b95-b3a7-97e3a48b2195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.</value>
      <webElementGuid>f7376a25-1d4a-4b3c-be73-9f4d77bff3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4c46553-d252-442e-b6cf-5392ade40590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c416143-991c-4f37-bdee-6fb690cfa2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;ui5-input-root ui5-input-focusable-element&quot;]/div[@class=&quot;ui5-input-content&quot;]/input[@id=&quot;ui5wc_19-inner&quot;]</value>
      <webElementGuid>709e935f-4c7e-4905-ba3f-023d3310e2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>390cf854-88d7-4f94-a8f1-0d147848554f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/xweb-shellbar-search-inputsearch-ome-d9b-f9d</value>
      <webElementGuid>d1fe1363-9e6c-446a-9968-453c7f24bf10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ui5wc_19-inner' and @type = 'text' and @placeholder = 'Search for actions or people']</value>
      <webElementGuid>ecf25bd4-23bd-4dc4-b757-de0ac1efbcd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
