<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ui5-button-sf-headerui5wc_1-item-1-d9b-c05-d38</name>
   <tag></tag>
   <elementGuidId>02a08b30-ee9d-4db7-9e65-9c765c90a93f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header.ui5-shellbar-root.ui5-shellbar-with-searchfield > div.ui5-shellbar-overflow-container.ui5-shellbar-overflow-container-right > div.ui5-shellbar-overflow-container-right-child > #ui5wc_1-item-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ui5-button-sf-header[@id = 'ui5wc_1-item-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui5wc_1-item-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-button-sf-header</value>
      <webElementGuid>95c94259-668d-48c2-b2e3-27647f22903a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>sap-icon://search</value>
      <webElementGuid>52085d65-8dc9-4b73-b224-0eaf764ab9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e223d4fb-e2f1-4e50-a885-07d623dab674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>toggle-search</value>
      <webElementGuid>170c1386-a620-49fd-90f0-6463489e87c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui5wc_1-item-1</value>
      <webElementGuid>855a9b36-366c-4447-bbfa-c7c8c3a878e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>   ui5-shellbar-button ui5-shellbar-search-button</value>
      <webElementGuid>815ee626-f443-494d-8458-b6f06732fc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>c25afaeb-1e18-4a37-99ed-a68b5d3dd552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/header[@class=&quot;ui5-shellbar-root ui5-shellbar-with-searchfield&quot;]/div[@class=&quot;ui5-shellbar-overflow-container ui5-shellbar-overflow-container-right&quot;]/div[@class=&quot;ui5-shellbar-overflow-container-right-child&quot;]/ui5-button-sf-header[@id=&quot;ui5wc_1-item-1&quot;]</value>
      <webElementGuid>fa9812f8-9a54-49d8-b2f9-301158033dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>54fdf279-7756-4ec3-882b-2b6fdde7acca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/ui5-shellbar-sf-header_HomeAdmin CentreCare_f5e95b</value>
      <webElementGuid>80039f37-66cd-47d4-ab90-a302cd366a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-button-sf-header[@id = 'ui5wc_1-item-1']</value>
      <webElementGuid>4ddebffc-14fd-4cb9-8a6f-856c0e86ab3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
