<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ui5-button-sf-headerui5wc_1-item-1-d9b-2fa-5be</name>
   <tag></tag>
   <elementGuidId>7fa55150-d8e1-4c69-8e1f-93d5bab13eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header.ui5-shellbar-root.ui5-shellbar-with-searchfield > div.ui5-shellbar-overflow-container.ui5-shellbar-overflow-container-right > div.ui5-shellbar-overflow-container-right-child > #ui5wc_1-item-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ui5-button-sf-header[@id = 'ui5wc_1-item-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui5wc_1-item-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-button-sf-header</value>
      <webElementGuid>d20d065a-b417-4742-9d2e-7f84ca8882d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>sap-icon://search</value>
      <webElementGuid>bd4a750e-438e-49e6-b5f7-1cf36669c6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f0764dd2-1c4f-4169-adbc-4d771e8b50f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>toggle-search</value>
      <webElementGuid>f91a72d4-1553-4cc2-a2df-35373067ea39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui5wc_1-item-1</value>
      <webElementGuid>af1a006c-86bd-45b8-a2f8-76417c6074b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>   ui5-shellbar-button ui5-shellbar-search-button</value>
      <webElementGuid>51f87f3e-7fc0-45da-be85-8e83e339178c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d92a0a76-0e1d-43eb-9b0c-809bf8133616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/header[@class=&quot;ui5-shellbar-root ui5-shellbar-with-searchfield&quot;]/div[@class=&quot;ui5-shellbar-overflow-container ui5-shellbar-overflow-container-right&quot;]/div[@class=&quot;ui5-shellbar-overflow-container-right-child&quot;]/ui5-button-sf-header[@id=&quot;ui5wc_1-item-1&quot;]</value>
      <webElementGuid>e62803e8-915f-46b8-91c1-6c4ad8936b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5483ce3c-723d-429b-afb4-945fe2250ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/ui5-shellbar-sf-header_HomeAdmin CentreCare_4c54ea</value>
      <webElementGuid>7d99ef84-c5f1-4637-9d04-a34a90623fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-button-sf-header[@id = 'ui5wc_1-item-1']</value>
      <webElementGuid>b4b54168-ce8e-4af7-8c13-9c90f5b9d13b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
