<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ui5-shellbar-sf-header_HomeAdmin CentreCare_4c54ea</name>
   <tag></tag>
   <elementGuidId>80c7dfa6-17b5-4852-85f7-3ef7eebcd290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > #shellbarContainer > #shellbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shellbarContainer']/ui5-shellbar-sf-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Home Admin Centre Careers Company Info Compensation My Employee File Objectives &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-shellbar-sf-header</value>
      <webElementGuid>af1cace8-14b1-485d-8992-921ae989d3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shellbar</value>
      <webElementGuid>48913b7f-7b5d-4b02-8cbf-ccd28c43ee4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>shellbar</value>
      <webElementGuid>69923b7c-660b-467b-8f41-963bc4869e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-static-stable</name>
      <type>Main</type>
      <value>shellbar-static</value>
      <webElementGuid>43523af9-7c9a-4685-975e-c52d2939c52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-fastnavgroup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d570f0d0-4dc3-402b-8e20-800aab57add2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>breakpoint-size</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>9d41e0ab-ca4d-43bf-bc08-1bfb93b87b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>primary-title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>380ce562-5855-4262-9cde-0ceb345dcf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents1 TackSearch “Tinne Tack” in Employee Directory</value>
      <webElementGuid>c119c2bf-1fae-4864-8dcb-1ec9a9135008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@id=&quot;shellbarContainer&quot;]/ui5-shellbar-sf-header[@id=&quot;shellbar&quot;]</value>
      <webElementGuid>099cf361-d569-48e9-8eca-d0676e5c7bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/xweb-shellbar_sfThemeRevealerdisplaynone-rs_228f83</value>
      <webElementGuid>bb7d0734-efd5-47b5-9e19-58e65eb55584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shellbarContainer']/ui5-shellbar-sf-header</value>
      <webElementGuid>bc407587-8c48-48ad-9596-c8d5dbf2dbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>5128f8e8-cbde-46be-b9c7-9484a8f744bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-shellbar-sf-header[@id = 'shellbar' and (text() = 'HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents1 TackSearch “Tinne Tack” in Employee Directory' or . = 'HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents1 TackSearch “Tinne Tack” in Employee Directory')]</value>
      <webElementGuid>075f0235-e7f8-40a9-b221-dcfa96387f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
