<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ui5-shellbar-sf-header_HomeAdmin CentreCare_f5e95b</name>
   <tag></tag>
   <elementGuidId>be9322e3-6d21-4d58-8e8a-ac071995db78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > #shellbarContainer > #shellbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shellbarContainer']/ui5-shellbar-sf-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Home Admin Centre Careers Company Info Compensation My Employee File Objectives &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-shellbar-sf-header</value>
      <webElementGuid>44c06966-f3ae-49fb-a452-3fe323441e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shellbar</value>
      <webElementGuid>c9534519-5e0f-4cf3-a45e-e3ed8d51613d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>shellbar</value>
      <webElementGuid>9946d760-7ef8-450b-af6b-dea46f7194a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-static-stable</name>
      <type>Main</type>
      <value>shellbar-static</value>
      <webElementGuid>e85a3dfb-9f5b-44f0-9b03-702cceda9938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-fastnavgroup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eeaa6de2-d965-4ec7-9cd6-8969cfda11d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>breakpoint-size</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>4886990c-9e6d-4e53-84bc-b340b488a3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>primary-title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>70726c6b-9897-4fc4-b247-6f23d3336199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents</value>
      <webElementGuid>57c6f288-2431-4939-957b-a397362e6c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@id=&quot;shellbarContainer&quot;]/ui5-shellbar-sf-header[@id=&quot;shellbar&quot;]</value>
      <webElementGuid>9b817c04-89af-4e5e-95ec-50e7b33907fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/xweb-shellbar_sfThemeRevealerdisplaynone-rs_228f83</value>
      <webElementGuid>edeeefeb-4f0f-4211-afc1-da2b04b422eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shellbarContainer']/ui5-shellbar-sf-header</value>
      <webElementGuid>c65ba5cc-bd16-4b5e-ac59-a70f8c18302f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>e5ff5812-ebb3-4549-8dfa-6a583d6d336d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-shellbar-sf-header[@id = 'shellbar' and (text() = 'HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents' or . = 'HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents')]</value>
      <webElementGuid>ecdd12b7-155e-4bde-8ac8-0df3aca09b7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
