<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xweb-shellbar_sfThemeRevealerdisplaynone-rs_228f83</name>
   <tag></tag>
   <elementGuidId>c81098cb-5c94-4520-a51e-7dda6c638c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>xweb-shellbar.sfEnsureSAPTheme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/xweb-shellbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>xweb-shellbar</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>xweb-shellbar</value>
      <webElementGuid>7aa42099-2953-48dd-9f8d-aea26384d6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sfEnsureSAPTheme</value>
      <webElementGuid>6a5ecf1e-139f-4bca-aca4-27bf88fe34fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>fcbce02f-7b09-456e-9ad5-13112cbfb2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>sf-header-shellbar</value>
      <webElementGuid>3a7c11f9-3c1e-4b06-abab-fbd10687d43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.sfThemeRevealer{display:none}</value>
      <webElementGuid>92e989be-a3af-46e2-98ea-9f226c505fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;Shell_shellBar__uauJv&quot;]/xweb-shellbar[@class=&quot;sfEnsureSAPTheme&quot;]</value>
      <webElementGuid>46aa4211-3411-4c37-a421-3c56e03b0afa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/xweb-shellbar</value>
      <webElementGuid>235d5bb9-3c90-4acb-8b8a-807c5ee3ef94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good afternoon!'])[1]/preceding::xweb-shellbar[1]</value>
      <webElementGuid>8d308dac-cd13-41b5-9f10-26e5af03879d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Actions'])[1]/preceding::xweb-shellbar[1]</value>
      <webElementGuid>39f62eef-c6a8-463f-8ada-1468f915c684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//xweb-shellbar</value>
      <webElementGuid>7f58db96-a142-42b7-bfc5-56febaaa4163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//xweb-shellbar[(text() = '.sfThemeRevealer{display:none}' or . = '.sfThemeRevealer{display:none}')]</value>
      <webElementGuid>a85c9bb3-917d-4d92-aba1-2d17bbaecce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
