<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xweb-shellbar-search-input_1 TackSearch Tin_baef7b</name>
   <tag></tag>
   <elementGuidId>07082961-7c0e-4e39-8f7c-f6c634c60145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > #shellbarContainer > #shellbar > #search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ui5-shellbar-sf-header[@id='shellbar']/xweb-shellbar-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;There were no results1 Tack Search “Tinne Tack” in Employee Directory Suggestion&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>xweb-shellbar-search-input</value>
      <webElementGuid>5be5bff0-5357-4bc5-a986-b3cd98dc5a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slot</name>
      <type>Main</type>
      <value>searchField</value>
      <webElementGuid>0f0ae56b-4da2-4e40-b70e-f3299b78a58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4ebcb8fe-11f6-4161-a859-6b8eac322ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>SearchField</value>
      <webElementGuid>e513660c-f1fe-4fc9-b1b1-1f4db4a729e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for actions or people</value>
      <webElementGuid>9ca2cbe6-8c2c-471c-a33c-4921b239e399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value-state</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>ffb750c4-a1eb-4726-a582-0ba476cfd38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible-name</name>
      <type>Main</type>
      <value>Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.</value>
      <webElementGuid>560a39b7-01af-45d2-806c-4c3211b89359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_input-width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>ce120a13-4e7e-4ac2-b317-e515907d2d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_list-width</name>
      <type>Main</type>
      <value>375</value>
      <webElementGuid>28e7c1a0-9147-48a7-a40f-8e1f22abcabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tinne Tack</value>
      <webElementGuid>df9da2a5-f045-44a4-a304-330b991ea880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 TackSearch “Tinne Tack” in Employee Directory</value>
      <webElementGuid>2909850c-2480-4ad2-9f32-a8ce3dd786e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@id=&quot;shellbarContainer&quot;]/ui5-shellbar-sf-header[@id=&quot;shellbar&quot;]/xweb-shellbar-search-input[@id=&quot;search&quot;]</value>
      <webElementGuid>efb3008a-78f3-4055-bec8-c6c7813d6eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/xweb-shellbar_sfThemeRevealerdisplaynone-rs_228f83</value>
      <webElementGuid>45cc292a-6846-4f2b-9403-107b52000ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ui5-shellbar-sf-header[@id='shellbar']/xweb-shellbar-search-input</value>
      <webElementGuid>bc08ff57-d748-4630-9e77-8bc8cb7b4361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>942c6c81-5109-4c9a-a13d-3abfcd6a4017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//xweb-shellbar-search-input[@id = 'search' and @placeholder = 'Search for actions or people' and (text() = '1 TackSearch “Tinne Tack” in Employee Directory' or . = '1 TackSearch “Tinne Tack” in Employee Directory')]</value>
      <webElementGuid>ff393a39-693d-4d2a-8d65-91c4d29289e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
