<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xweb-shellbar-search-input_Tinne TackSearch_695e91</name>
   <tag></tag>
   <elementGuidId>015ecf81-290d-495c-90f3-b10dd033d041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > #shellbarContainer > #shellbar > #search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ui5-shellbar-sf-header[@id='shellbar']/xweb-shellbar-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;There were no resultsTinne Tack Search “Tinne Tack” in Employee Directory Sugges&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>xweb-shellbar-search-input</value>
      <webElementGuid>80d21357-5185-464d-8e0a-dd875d849c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slot</name>
      <type>Main</type>
      <value>searchField</value>
      <webElementGuid>33c0c181-7034-4f96-9a82-e5ad52bea58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>43fe1f98-56a1-4a07-8608-8a5f52b78cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>SearchField</value>
      <webElementGuid>449a106d-5218-419c-be2a-60d2c7735aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for actions or people</value>
      <webElementGuid>bbd0055b-afc6-45c0-a41c-dc5ca89e7979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value-state</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>a6cebf62-8164-470b-b0ee-50b422a5f9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible-name</name>
      <type>Main</type>
      <value>Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.</value>
      <webElementGuid>c3def6c5-9102-4834-bab1-55acf6c2f7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_input-width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>2914b026-24f2-4da9-8406-7d026b234578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_list-width</name>
      <type>Main</type>
      <value>375</value>
      <webElementGuid>69b484d4-6991-44a4-90b0-f43d20d8de17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tinne Tack</value>
      <webElementGuid>a46f0e8c-b935-4cb1-99f2-d79c5d96e73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tinne TackSearch “Tinne Tack” in Employee Directory</value>
      <webElementGuid>387e0c4a-7b79-4b01-bd52-56d6d23c258d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@id=&quot;shellbarContainer&quot;]/ui5-shellbar-sf-header[@id=&quot;shellbar&quot;]/xweb-shellbar-search-input[@id=&quot;search&quot;]</value>
      <webElementGuid>bb2fe9e8-da6d-44f9-ada2-0b8ec04eeb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa15f369-7b79-4410-8bec-3a2c4ad0b5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/xweb-shellbar_sfThemeRevealerdisplaynone-rs_228f83</value>
      <webElementGuid>f37b3811-5f77-4bf9-8ce5-5a9dc4046636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ui5-shellbar-sf-header[@id='shellbar']/xweb-shellbar-search-input</value>
      <webElementGuid>176bda9f-516c-402a-9e0d-c0d70684f030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>2c6903ee-160b-43f6-8f5f-68a980b0c518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//xweb-shellbar-search-input[@id = 'search' and @placeholder = 'Search for actions or people' and (text() = 'Tinne TackSearch “Tinne Tack” in Employee Directory' or . = 'Tinne TackSearch “Tinne Tack” in Employee Directory')]</value>
      <webElementGuid>6cfa2ca4-7d1b-4829-ae5d-29cb7e1ed706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
