<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xweb-shellbar-search-input_Els SchelfhoutEl_a28334</name>
   <tag></tag>
   <elementGuidId>f176f9f9-e0c2-45e4-a7f2-48503d8a29a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > #shellbarContainer > #shellbar > #search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ui5-shellbar-sf-header[@id='shellbar']/xweb-shellbar-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;There were no resultsEls Schelfhout Els Vanden driessche Els Bas Els Behets Els &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>xweb-shellbar-search-input</value>
      <webElementGuid>905494bd-c1a5-41b4-8eac-ad1676c6b8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slot</name>
      <type>Main</type>
      <value>searchField</value>
      <webElementGuid>284f86b6-37e0-450f-bb1d-15b881c70a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>1b978e4e-874f-47db-812f-05063919cd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>SearchField</value>
      <webElementGuid>bb290354-1215-416b-b4dc-d238dc5986c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for actions or people</value>
      <webElementGuid>883ee9db-0b0d-43c5-a3fa-418b037d8106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value-state</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>29f4e611-9474-4aea-98dc-a5166a88e47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible-name</name>
      <type>Main</type>
      <value>Auto-complete search results are shown after you enter at least 2 characters. When results are shown, use the UP and DOWN arrow keys to navigate the list of actions and people. When focus is on a person in search results, press the CTRL + SHIFT + 1 keys to move focus to the employee quickcard for that person. Press F6 to select the Employee Directory.</value>
      <webElementGuid>02c88f6f-ea96-4d14-a3c5-85700ffe93a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_input-width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>3e7be0cd-d04f-4caf-8863-8ad17ab376ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_list-width</name>
      <type>Main</type>
      <value>421</value>
      <webElementGuid>c2def7f7-eda3-4224-8352-22fabcf537ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ees</value>
      <webElementGuid>8a24d2b8-e592-4d1c-b244-4d3ae3395878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Els SchelfhoutEls Vanden driesscheEls BasEls BehetsEls BerghmansEls ClaesEls ConinxEls De BelieEls De KerpelEls De PuysseleyrSearch “ees” in Employee Directory</value>
      <webElementGuid>70156e95-33ec-48d2-a7e5-842dee727181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@id=&quot;shellbarContainer&quot;]/ui5-shellbar-sf-header[@id=&quot;shellbar&quot;]/xweb-shellbar-search-input[@id=&quot;search&quot;]</value>
      <webElementGuid>aec90714-abb9-4a01-ba05-2584ac1a1192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/xweb-shellbar_sfThemeRevealerdisplaynone-rs_228f83</value>
      <webElementGuid>96c50fa1-ff13-4f7f-90c6-067a760efe8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ui5-shellbar-sf-header[@id='shellbar']/xweb-shellbar-search-input</value>
      <webElementGuid>ee1c0c6f-a5e6-457c-838d-e1c5e1bad30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>434d5995-65ef-44aa-a6d9-0777878701a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//xweb-shellbar-search-input[@id = 'search' and @placeholder = 'Search for actions or people' and (text() = 'Els SchelfhoutEls Vanden driesscheEls BasEls BehetsEls BerghmansEls ClaesEls ConinxEls De BelieEls De KerpelEls De PuysseleyrSearch “ees” in Employee Directory' or . = 'Els SchelfhoutEls Vanden driesscheEls BasEls BehetsEls BerghmansEls ClaesEls ConinxEls De BelieEls De KerpelEls De PuysseleyrSearch “ees” in Employee Directory')]</value>
      <webElementGuid>68d6aa79-c194-4eac-b795-012720ecab4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
