<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sign in_lnXdpd</name>
   <tag></tag>
   <elementGuidId>525940a7-a448-4fd0-85ce-176cf4a4a84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.lnXdpd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Google']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Google&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>04b431f7-4e84-43a8-88f7-78b5f01034e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnXdpd</value>
      <webElementGuid>23baeb82-c446-40fd-853f-2fa1443638c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>826830b1-6653-4b8e-836b-2ffd588e69cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>92</value>
      <webElementGuid>400d7dca-d629-40fe-a872-87a57f9621be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png</value>
      <webElementGuid>a36b614b-5b62-412e-8aa1-567e81dad171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png 1x, /images/branding/googlelogo/2x/googlelogo_color_272x92dp.png 2x</value>
      <webElementGuid>f56a4b2a-7118-4473-92e9-994a82c80d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>272</value>
      <webElementGuid>beb88034-9729-4d5e-b9eb-188ed125b556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csiid</name>
      <type>Main</type>
      <value>sYm0Z_qYFMnQhbIP9rKB0Ag_1</value>
      <webElementGuid>883848d0-f6fe-43d7-94ab-2ceb2a0cc859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7bdbd92d-ec2b-4ad5-b587-702d3ca72741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 LLD4me yr19Zb LS8OJ&quot;]/div[@class=&quot;k1zIA rSk4se&quot;]/img[@class=&quot;lnXdpd&quot;]</value>
      <webElementGuid>68c01343-7016-4f5b-9a1e-9ded0b15bd13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Google']</value>
      <webElementGuid>087cbe60-65e9-4478-a642-4dcff67e402d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c30db822-d010-4b3b-a256-7619c60a28d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Google' and @src = '/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png']</value>
      <webElementGuid>fc30e4da-f14e-4521-9146-29a31bb54d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
