<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>46ab973f-34bc-468d-a1d8-e3889dcb6416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Cru&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Cru']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cru Home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>095c436f-db8a-4f18-af64-e2ea196b413d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.cru.be/build/images/logo.0e713552.png</value>
      <webElementGuid>918120df-6b47-4aa9-8b59-52723a1b482f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cru</value>
      <webElementGuid>0116527a-6474-41b1-81cb-b0eb3fd08f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>4310a527-5f33-432f-9159-35a278bba5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js wf-robotoslab-n3-active wf-robotoslab-n4-active wf-robotoslab-n5-active wf-robotoslab-n6-active wf-robotoslab-n2-active wf-roboto-n4-active wf-roboto-n5-active wf-roboto-n1-active wf-roboto-n3-active wf-active&quot;]/body[1]/div[@class=&quot;page-wrap&quot;]/header[@class=&quot;page-header | js-header&quot;]/div[@class=&quot;page-header__main&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-header__content&quot;]/a[@class=&quot;page-header__logo&quot;]/img[1]</value>
      <webElementGuid>c5148d43-9e8e-4e26-86b2-abea0c0838c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cru']</value>
      <webElementGuid>e154c58b-54ad-455e-91a7-0361bffd7818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f0904d72-2d74-4673-8111-6ef6b191a7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.cru.be/build/images/logo.0e713552.png' and @alt = 'Cru']</value>
      <webElementGuid>7bef8d69-4843-417e-b24d-20672faad037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
