<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ui5-shellbar-sf-header_HomeAdmin CentreCare_acdf27</name>
   <tag></tag>
   <elementGuidId>842a2996-7d55-401b-bded-5eae8687087d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > #shellbarContainer > #shellbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shellbarContainer']/ui5-shellbar-sf-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Home Admin Centre Careers Company Info Compensation My Employee File Objectives &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-shellbar-sf-header</value>
      <webElementGuid>67f40b70-576d-419f-b46b-24fc632b7f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shellbar</value>
      <webElementGuid>52642ca5-8290-4ead-a6c7-c8a3e0912d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>shellbar</value>
      <webElementGuid>14f3a98e-977a-4640-a0fd-12efc1aa89c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-static-stable</name>
      <type>Main</type>
      <value>shellbar-static</value>
      <webElementGuid>69a117f0-6da1-4f68-8d35-be8d5caa6854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-fastnavgroup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a2de21d1-e8fb-4b8f-b4d0-38cdd55b99a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>breakpoint-size</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>b8196544-a2e0-432e-9b4f-f928d0ef3771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>primary-title</name>
      <type>Main</type>
      <value>My Employee File</value>
      <webElementGuid>52ac1ec0-1691-441f-9727-22adc541ca4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents</value>
      <webElementGuid>dfc638f8-9cc4-4965-a0b6-255cfba724d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@id=&quot;shellbarContainer&quot;]/ui5-shellbar-sf-header[@id=&quot;shellbar&quot;]</value>
      <webElementGuid>693af92a-26a7-4a1b-a5ad-1d0c23aaaed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>550cf1e8-dd91-47f3-999b-2a87d35635c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors People Profile for Juli_6d183c/xweb-shellbar_sfThemeRevealerdisplaynone-oo_452d6e</value>
      <webElementGuid>75ebaf75-47d5-4fe4-9507-aad68bca01b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shellbarContainer']/ui5-shellbar-sf-header</value>
      <webElementGuid>b2d13763-51b1-4f7d-b917-a6cfa5a2ba47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>8be29bf9-8907-40d3-807b-c6c0808251f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-shellbar-sf-header[@id = 'shellbar' and (text() = 'HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents' or . = 'HomeAdmin CentreCareersCompany InfoCompensationMy Employee FileObjectivesPerformanceRecruitingReportingPersonnel Documents')]</value>
      <webElementGuid>ac4e2d2a-ac72-498f-b31e-b041f0111bf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
