<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ui5-button-sf-headerui5wc_1-item-1-bd4-9a8-d97</name>
   <tag></tag>
   <elementGuidId>3fcfbfcc-b941-4c56-b2e2-a58a6dd7b73f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header.ui5-shellbar-root.ui5-shellbar-with-searchfield > div.ui5-shellbar-overflow-container.ui5-shellbar-overflow-container-right > div.ui5-shellbar-overflow-container-right-child > #ui5wc_1-item-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ui5-button-sf-header[@id = 'ui5wc_1-item-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui5wc_1-item-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-button-sf-header</value>
      <webElementGuid>b32f5cec-618a-4fc6-ab8d-3087543194d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>sap-icon://search</value>
      <webElementGuid>f21472a7-ae7b-449e-946c-ab0cf3ae94c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>341a0323-b7be-4fd9-80b8-24189472c73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>toggle-search</value>
      <webElementGuid>f727acd7-e3cd-43af-8b43-f2236711b93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui5wc_1-item-1</value>
      <webElementGuid>eea05213-b9d9-4b0a-a021-f6c9bdc6c068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>   ui5-shellbar-button ui5-shellbar-search-button</value>
      <webElementGuid>5ed7c5a3-0db6-431b-9334-879fd54f3abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>588d91d3-fcc0-4943-bc38-628489d4bb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/header[@class=&quot;ui5-shellbar-root ui5-shellbar-with-searchfield&quot;]/div[@class=&quot;ui5-shellbar-overflow-container ui5-shellbar-overflow-container-right&quot;]/div[@class=&quot;ui5-shellbar-overflow-container-right-child&quot;]/ui5-button-sf-header[@id=&quot;ui5wc_1-item-1&quot;]</value>
      <webElementGuid>b1c8a6cb-b99e-488b-86da-290a58d6a87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b50c29e0-0b7f-4f15-a01c-29029fe02527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors People Profile for Juli_6d183c/ui5-shellbar-sf-header_HomeAdmin CentreCare_acdf27</value>
      <webElementGuid>f531e1cf-6a58-4945-a528-01bf0887939a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-button-sf-header[@id = 'ui5wc_1-item-1']</value>
      <webElementGuid>ebfa9f1f-ba3e-4ded-821f-2894d5cdfaa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
