<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xweb-shellbar_sfThemeRevealerdisplaynone-oo_452d6e</name>
   <tag></tag>
   <elementGuidId>fdfbd668-8bc1-4261-86d7-775bd1b855bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>xweb-shellbar.sfEnsureSAPTheme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bizXShellBarContainer']/xweb-shellbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>xweb-shellbar</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>xweb-shellbar</value>
      <webElementGuid>990a5a43-3af5-4f33-a7fd-516ee9062626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sfEnsureSAPTheme</value>
      <webElementGuid>b35e134f-67a1-48fc-9069-98b1c0dc3232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>ad939b65-b6c3-4c0f-a128-6c61759879ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>sf-header-shellbar</value>
      <webElementGuid>6db350f6-fc57-4f66-ae63-5407b007cfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.sfThemeRevealer{display:none}</value>
      <webElementGuid>d215ca84-a740-4f0a-a078-4b2d2cbbaa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bizXShellBarContainer&quot;)/xweb-shellbar[@class=&quot;sfEnsureSAPTheme&quot;]</value>
      <webElementGuid>ed375632-6ba0-4cfd-a4e6-b203ee075d6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bizXShellBarContainer']/xweb-shellbar</value>
      <webElementGuid>19823ddb-7402-4fe3-9b5b-2bc8b9e27ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Julie Spoormans'])[1]/preceding::xweb-shellbar[1]</value>
      <webElementGuid>be084d66-c94b-4077-ac35-ddf0b67b31fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Julie Spoormans'])[2]/preceding::xweb-shellbar[1]</value>
      <webElementGuid>918dc9e0-91d4-4556-9b3b-3a8329920f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//xweb-shellbar</value>
      <webElementGuid>7598fa36-8cc3-42e2-a664-a828218cef6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//xweb-shellbar[(text() = '.sfThemeRevealer{display:none}' or . = '.sfThemeRevealer{display:none}')]</value>
      <webElementGuid>823207c6-75ac-497d-bc8f-e6f3e6c7c57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
