<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Already installed</name>
   <tag></tag>
   <elementGuidId>a41ec4c0-af21-47b6-a2d6-ee61f9479b44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#protocolhandler-detect-alreadyInstalledLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='protocolhandler-detect-alreadyInstalledLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Already installed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8ecda85-2307-4197-a4be-4c2fe57f4c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>protocolhandler-detect-alreadyInstalledLink</value>
      <webElementGuid>9ac9ce34-1bcc-4dbf-ab35-c6b201ab8c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>detect-already-installed web-screen-link _ctxstxt_AlreadyInstalled</value>
      <webElementGuid>f44365af-0e78-40fe-a775-5a94fb315042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c4c8a552-485c-4c8b-9116-2f3b04c89038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Already installed</value>
      <webElementGuid>78f5d03b-85e3-4077-b5be-c64e21c85772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;protocolhandler-detect-alreadyInstalledLink&quot;)</value>
      <webElementGuid>5c6d6788-523d-4319-9f88-f59974a77d65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='protocolhandler-detect-alreadyInstalledLink']</value>
      <webElementGuid>bc36ccf1-9269-424b-8d27-fc74c0957fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='protocolhandler-detect']/div/div/div/div/div/a[3]</value>
      <webElementGuid>0583b2ca-dcfd-4650-983d-9b377f1c5014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Already installed')]</value>
      <webElementGuid>bb9f0ca3-1eca-42eb-ba3c-995fdc6c17f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[4]/following::a[1]</value>
      <webElementGuid>d28cc60f-7134-435e-a648-ed0eb0655d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[3]/following::a[2]</value>
      <webElementGuid>ceea9122-6183-4787-ba81-ce85cfa447a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[5]/preceding::a[1]</value>
      <webElementGuid>474595e5-aed3-4d88-8eaf-ecf0dd7cff49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please accept the terms of the licensing agreement before installing Citrix Workspace app.'])[2]/preceding::a[2]</value>
      <webElementGuid>95730b12-ab5f-4b36-99dd-410c1a8747b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[80]</value>
      <webElementGuid>c1e023c8-4fc9-4506-bcd1-e1e39e3d8476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a[3]</value>
      <webElementGuid>3eabe18c-865d-45c2-adf8-14000c7ff6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'protocolhandler-detect-alreadyInstalledLink' and @href = '#' and (text() = 'Already installed' or . = 'Already installed')]</value>
      <webElementGuid>09fb6cce-749b-4545-86e6-df231abef159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
