<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>eaa19b3a-b552-42cc-82c7-ac618a1131fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#protocolhandler-detect-downloadButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='protocolhandler-detect-downloadButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Download&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a9edcd4-8621-4856-b1a5-159aa1560021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>protocolhandler-detect-downloadButton</value>
      <webElementGuid>ea1b73eb-7cbb-441b-bd87-b8aa1fd4a727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>installbutton default button _ctxstxt_Download</value>
      <webElementGuid>ac8e68c8-4cdf-4c0c-a7e0-dda15f94d9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://downloadplugins.citrix.com/Windows/CitrixWorkspaceApp.exe</value>
      <webElementGuid>c2fe7b6f-62cb-4c04-8b9d-6ac5156cd752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>4473b712-252c-4965-bb11-185cc85b1266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;protocolhandler-detect-downloadButton&quot;)</value>
      <webElementGuid>91dae226-f54f-4082-8210-00c1297adaf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='protocolhandler-detect-downloadButton']</value>
      <webElementGuid>8f1def78-ccb3-4878-ba46-d1b6572e97d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='protocolhandler-detect']/div/div/div/div/a</value>
      <webElementGuid>b1a05f32-6d77-48b5-9966-c063a7f40ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>0ffc568b-9f1b-45aa-b657-9013ae648f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree with the'])[2]/following::a[2]</value>
      <webElementGuid>6a2ca886-0f31-4b80-b195-ef5ab92b4338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already installed'])[1]/following::a[2]</value>
      <webElementGuid>cb24fd27-13b3-4b28-8682-30afbf2e9021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[3]/preceding::a[2]</value>
      <webElementGuid>6ed94350-9aac-4730-8d41-bfb14192beb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[4]/preceding::a[3]</value>
      <webElementGuid>bd4e8a95-e31d-46a9-88c2-858567b6b729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://downloadplugins.citrix.com/Windows/CitrixWorkspaceApp.exe')]</value>
      <webElementGuid>7e0fc073-2d3f-4b55-a8bc-f5f9e4fd263b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[16]/div/div/div/div/a</value>
      <webElementGuid>e6b16036-58d4-4526-bfb1-57a9f4756516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'protocolhandler-detect-downloadButton' and @href = 'https://downloadplugins.citrix.com/Windows/CitrixWorkspaceApp.exe' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>d9ee07f7-da50-4477-90e5-71ca28ee0698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
