<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open</name>
   <tag></tag>
   <elementGuidId>854ca8ce-aafa-4701-a4bd-2968b4f7fb0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.theme-highlight-color.appDetails-actions-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home-screen']/div[2]/section[5]/div[5]/div/ul/li/div[3]/div[2]/table/tr/td/div/a/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Open&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc994525-a2af-489b-8eb1-e880c1be848f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-highlight-color appDetails-actions-text</value>
      <webElementGuid>4ff7c300-9bf7-43d2-90d4-bd2f2726de01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open</value>
      <webElementGuid>02d82800-bdea-4d89-a299-4a7f73eb8079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-screen&quot;)/div[@class=&quot;home-view-content&quot;]/section[@class=&quot;scrollable storeViewSection&quot;]/div[@class=&quot;store-apps-container&quot;]/div[@class=&quot;store-apps-group&quot;]/ul[@class=&quot;storeapp-list&quot;]/li[@class=&quot;storeapp added showDetails theme-highlight-border-color&quot;]/div[@class=&quot;storeapp-details-dropdown theme-highlight-border-color hidden&quot;]/div[@class=&quot;appDetails-container&quot;]/table[@class=&quot;appDetails-container-table&quot;]/tr[@class=&quot;appDetails-container-tr&quot;]/td[@class=&quot;appDetails-actions-container&quot;]/div[@class=&quot;appDetails-actions-header&quot;]/a[@class=&quot;appDetails-action-launch&quot;]/div[@class=&quot;appDetails-actions-item&quot;]/div[@class=&quot;theme-highlight-color appDetails-actions-text&quot;]</value>
      <webElementGuid>f290770f-d247-4e70-b8db-724f8b4d4eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home-screen']/div[2]/section[5]/div[5]/div/ul/li/div[3]/div[2]/table/tr/td/div/a/div/div[2]</value>
      <webElementGuid>09bc6f35-ef23-411a-a89c-1c716986940e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/following::div[5]</value>
      <webElementGuid>d00f6c11-12d2-4c1a-a545-dc9b16df0ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add To Favorites'])[1]/preceding::div[2]</value>
      <webElementGuid>45bf791e-c91b-42a7-8b1b-95c77328201f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove from favorites'])[1]/preceding::div[5]</value>
      <webElementGuid>54d433e5-5f1e-4785-a42e-7894428cdf3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open']/parent::*</value>
      <webElementGuid>5734d27b-968c-45f7-be9d-1fc54a1ba1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]</value>
      <webElementGuid>d9bf2a52-04d1-46bf-aa6d-2b854bff26af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Open' or . = 'Open')]</value>
      <webElementGuid>ad3d233c-e01f-497a-93f0-de3b5a5a2063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
