<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Already installed_legalstatement-checkbox2</name>
   <tag></tag>
   <elementGuidId>9b117a69-badd-4c5f-bfaf-8f6b06ff24d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#legalstatement-checkbox2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='legalstatement-checkbox2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox[name=&quot;I agree with the Citrix license agreement&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80739ae3-31fe-4ca7-a514-49a068e8a08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>legalstatement-checkbox2</value>
      <webElementGuid>20d27b47-e535-4cd8-8224-6bfa195105ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>legalstatement-checkbox</value>
      <webElementGuid>b4217c0b-369c-4a66-a0bb-ec2c7bd2aa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3131d47c-37a8-4100-9693-90bbf293e77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;legalstatement-checkbox2&quot;)</value>
      <webElementGuid>22cc3799-a712-4754-a49f-9d5f1bf4647c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='legalstatement-checkbox2']</value>
      <webElementGuid>577c14af-06fc-44d9-a131-7e16f84f63de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='protocolhandler-detect']/div/div/div/div/p[4]/input</value>
      <webElementGuid>fd9b2bcc-c0dd-43df-9eea-84de717459ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>12dbcbf9-ccc1-4aff-84f9-22bf9459ba39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'legalstatement-checkbox2' and @type = 'checkbox']</value>
      <webElementGuid>cca440db-cde4-43f4-9000-c46c3e71a31a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
