<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_About this page_a-r4idlrqz2r0c</name>
   <tag></tag>
   <elementGuidId>1ae5ffb4-0527-43a8-945c-1149736dc7fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-r4idlrqz2r0c&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-r4idlrqz2r0c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-r4idlrqz2r0c&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e8cfa1f4-2bf5-4c74-a6e2-72cc509f733f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>9c86c7e6-41f2-452b-99ab-e6f3d442c11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>ea945fa4-6196-4a57-a594-b60a53eb8c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>cc552108-82d5-46a1-b11b-e4f5dd5027a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>def9ed81-65c9-47d6-b8d7-94b5b27ff839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-r4idlrqz2r0c</value>
      <webElementGuid>23e92590-ad1a-4a59-8ea5-a224e007a43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a602ea04-d41b-42c2-b7ef-0b7921fd68d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>223d6e3e-8785-4265-a5cf-44ffa8a85428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>b9f88577-8f99-41e3-91f8-1cb17b52f9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;size=normal&amp;s=82Wrv6thqXl4GBXsZWyQq1VFU95jXsc0mPXKrXmVoT7d1TFFaxj4XO2HoO9_easVxDxlpsIEgS2vOnlze8o1bSX3-xYAke9au16tt3dFGVlMFPtoe_tKVe_iXa64jgg9lshkyR9rFdmP1dbWhFq-MDXnPym0PJ92EiAshtsW1UjPj3R5xuAjFYdCs1FoftxdfT2pXnX3jMKchLI9sCv6W1I1DvXO7QH1oruIET4YOOnjaS96GLwHvUz8DTn2PugsZoMuCy9onVz9CGI8SSYMVRq6pG3uUtw&amp;cb=7otdsan03v6b</value>
      <webElementGuid>0cfc6566-5ee9-4bcb-be0d-3f9b71136add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>08ba6f42-ac68-42a3-bca4-34da2382ebd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-r4idlrqz2r0c']</value>
      <webElementGuid>a7998496-03a1-494e-a34b-a691c72392e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha']/div/div/iframe</value>
      <webElementGuid>8b509f3c-d2e1-41fa-8737-096ddd8a5996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>073b6985-a895-432b-ae7b-f4a36fc89d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-r4idlrqz2r0c' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;size=normal&amp;s=82Wrv6thqXl4GBXsZWyQq1VFU95jXsc0mPXKrXmVoT7d1TFFaxj4XO2HoO9_easVxDxlpsIEgS2vOnlze8o1bSX3-xYAke9au16tt3dFGVlMFPtoe_tKVe_iXa64jgg9lshkyR9rFdmP1dbWhFq-MDXnPym0PJ92EiAshtsW1UjPj3R5xuAjFYdCs1FoftxdfT2pXnX3jMKchLI9sCv6W1I1DvXO7QH1oruIET4YOOnjaS96GLwHvUz8DTn2PugsZoMuCy9onVz9CGI8SSYMVRq6pG3uUtw&amp;cb=7otdsan03v6b']</value>
      <webElementGuid>7e27538a-5cbe-428e-84b8-f897f2578adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
