<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3</name>
   <tag></tag>
   <elementGuidId>dafe373e-f27f-4c25-a694-98b087265123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc02aab9-dcde-470a-aa16-e34242fe5959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>8674a659-9c0f-4565-b050-f2e277fb5085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>e98f2cc4-64e9-41c6-a787-2b85ebe3e009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>d2d9ca0d-9576-4971-87b9-c4781dabe730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>69891784-abe1-4f43-8fc8-ee068585afcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>c82df119-ea41-45a2-8c3d-a66101cbd636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[6]</value>
      <webElementGuid>390cc988-0098-4475-80fb-77eb2e8a724b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>0bc591f1-4908-4cad-b9b6-bd56305a8f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>9cb56b5b-9f81-4ef6-bd06-a68d45ed93d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
