<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>56a93433-9ce1-440a-b70b-d398ee7e0600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5575040-eaec-4398-bd08-9321a7714a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>ace1b7af-e25d-4853-b68b-129e17e297a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2</value>
      <webElementGuid>2d05ebad-d6cb-46d8-ac4d-57945f0af472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>a24ca689-43eb-4828-98e9-468e0f887379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>bc7f2d5b-e6f9-48cf-a972-04234e305ae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      <webElementGuid>cd2517c4-6e4f-41a4-b16d-8b570611a911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2')])[15]</value>
      <webElementGuid>224c2ee6-f2d6-4470-a9f0-23ba188cce28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/div/div/img</value>
      <webElementGuid>1ac0d035-9582-4f8e-a21d-ca1a89c78db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2']</value>
      <webElementGuid>ae7ce397-da67-4b9f-9adc-95bc1213f88b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
