<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3</name>
   <tag></tag>
   <elementGuidId>c9e082a0-4d35-4881-87aa-31efab154b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>413c3e3a-8c60-4ffa-963f-f79620fea9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>60737ca2-9c9b-4653-b71f-c2b1d9cab209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>a04f432d-4040-4cbd-96fe-b7b2fe1bdf3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>f364f7b0-c01c-48db-b6e4-e323d6e25b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>fa041794-e8f3-43d6-9653-76cdecfb13aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>0912d64a-a733-4d49-a49b-0c67c6bf1d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[10]</value>
      <webElementGuid>74bd77f5-72b4-4932-b640-8d38bf46ed2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>b331983b-f4a0-4de2-9749-e950f46add32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>73b4e564-c8b0-4a72-9040-3d0ff1c98915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
