<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21</name>
   <tag></tag>
   <elementGuidId>fe7c1efa-a108-44e0-b614-de45e3da4ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9500edc4-7707-41d5-a24a-ec8de4ca0c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>d432d006-1fd1-4833-9235-2d7c392e0e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56</value>
      <webElementGuid>5bb98f6b-0b94-4912-bb09-56ec88865ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>98f3a5b0-b364-4cac-add5-253f8ca92d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>9aed70c9-9d4c-4907-a894-4e76adaadcc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[4]/div/div/img</value>
      <webElementGuid>1de4706b-d596-4563-8c24-0847a8a15bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56')])[16]</value>
      <webElementGuid>2a98a8cd-62f8-4bbe-85a7-df583d151247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/div/div/img</value>
      <webElementGuid>9f193dbd-88bb-4c5c-8466-288c775db5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56']</value>
      <webElementGuid>a5eb79c5-b69f-4268-88e7-9cc1ec14ac0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
