<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28</name>
   <tag></tag>
   <elementGuidId>d882ca06-7a1f-4a7d-8955-ebcc503ffc0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>476ab013-4f36-47ad-9493-efe7b4eed247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>70f1521b-bf2a-402a-85d0-69b487e26980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18</value>
      <webElementGuid>36b8b50e-5ed5-4939-ad8d-51cb657b0536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b120586d-075c-4ffd-b861-21967290c280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>8c202379-4fdf-4e24-956e-96f645e1280b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      <webElementGuid>9d35490d-3ee4-45bd-a594-3157e7eff9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18')])[12]</value>
      <webElementGuid>624aa741-1923-43f0-bca6-2aa5f228917b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
      <webElementGuid>c6b431ab-1a92-48f0-be72-1de42a1b46a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18']</value>
      <webElementGuid>fce90895-355e-4b91-a991-e51fb808cf9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
