<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22</name>
   <tag></tag>
   <elementGuidId>fb1af31d-c820-406c-8e1c-0c72ec9cf2df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>066f4002-c29f-41d4-8a5d-78bfdab9f709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>af95bfe6-31ba-4c79-b55a-18518a49f67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56</value>
      <webElementGuid>fff5fdf8-cb2e-4c07-a2b1-6d79d972f7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>2109c297-8e31-46cf-b55c-85f3775fdc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>505e941f-75c5-4474-b593-50451764d2ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      <webElementGuid>d11a691f-cc44-4274-9640-e1bea834aeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56')])[15]</value>
      <webElementGuid>97fcb828-30b1-44ce-903f-1aeb8b8a3508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/div/div/img</value>
      <webElementGuid>0fcfe830-b09c-4109-9fa0-328baa4ffe5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56']</value>
      <webElementGuid>23a0e905-f7c4-404d-8358-8900dfb5d463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
