<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>7f54338c-9d1d-4b86-a679-babed693cd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b2e23bf2-4d6a-4025-a16a-d7eb8384cd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>5c6d19b5-d952-4768-ab18-fbd9ea92a434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2</value>
      <webElementGuid>17976f2d-30bc-4b37-8baa-faaedc8c3739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>2d279ab0-7779-4e1c-8d9b-be5e63262b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>7f8a3769-9028-40da-a2af-0c611b0f4452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      <webElementGuid>506ebe67-522e-4f87-84b6-964ad2c265fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2')])[14]</value>
      <webElementGuid>59792b12-effd-4988-bca8-7d063763192f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/img</value>
      <webElementGuid>874da3d3-3a9b-405b-a977-390e72c3f3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2']</value>
      <webElementGuid>961b0337-e043-4c00-aef5-7a3f6ea766f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
