<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18</name>
   <tag></tag>
   <elementGuidId>543e8459-e9b8-4cbe-a658-74e211e8c569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cda11b6e-b3a7-4847-8c56-98c205f35c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>ef248eea-d6ec-49be-88f1-c0987872976a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3</value>
      <webElementGuid>24169702-0086-40f3-8369-b3de451f5f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>f2e61192-07ea-4007-87c9-2c332ffd3894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>e4a643e8-3bc6-4f4c-96eb-1d9537847173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>1483f214-5a1b-4a9f-ad1f-8e2e58db7f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3')])[11]</value>
      <webElementGuid>9fc9fa36-7792-4ead-9d55-0f60d3567215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>ef22513d-3066-442a-9f40-823d3d511736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3']</value>
      <webElementGuid>80138218-63ac-4058-8e2a-e7e434493736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
