<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25</name>
   <tag></tag>
   <elementGuidId>951d65a1-d71b-443f-b848-08190f035ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd3db7f5-c8fe-4276-a721-6f893802acfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>a9a2eda2-e408-41f3-8600-fca573c75926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18</value>
      <webElementGuid>72af0aa0-0bd0-4ea2-b974-5a0e73ca8aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>8116e0b5-d556-4ae3-a93e-fa7663531159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>c00c9250-9c45-45e4-829c-5393c203489c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>8787d58a-91cb-42ba-929c-4dd1ede149ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18')])[7]</value>
      <webElementGuid>30b8ffbb-fc67-4641-af8b-911446f5b684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>69473831-19b6-4daa-b3b1-65de02148677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18']</value>
      <webElementGuid>4d50babc-2ffc-4f06-a20e-d3365288809d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
