<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20</name>
   <tag></tag>
   <elementGuidId>d80b1f41-134b-4a3a-97d4-b42c09087a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d03596aa-6fc7-4595-a522-6f1afab1180c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>333baa73-515a-4491-b414-ecfd2a201e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56</value>
      <webElementGuid>44f1ee49-b805-43ad-8b51-5768825f2bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>775e244f-1cb7-44be-a14b-3d71670c134a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>33ffe8ee-6388-4fff-bb3e-782835e83920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      <webElementGuid>91dc6f12-bf35-403b-91f3-ccf831aae139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56')])[12]</value>
      <webElementGuid>13bc809f-9842-4bc8-8485-ac008f87d532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
      <webElementGuid>040cb209-a8e6-4d65-8914-8ee527a51da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56']</value>
      <webElementGuid>3663ca0c-5669-4b1f-b7a9-6d3ada5d10c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
