<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15</name>
   <tag></tag>
   <elementGuidId>e030a9ef-3499-449c-96f8-8c47d3d103b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4ee5824-68fe-4ac9-955e-989e53ea531e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>51326dd1-a135-4d0f-8a61-4218e2c1b24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3</value>
      <webElementGuid>93ef9b5a-72a1-4ca5-a176-e95e4a142172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>d8a5029f-f651-478c-9c49-3a14aabfb2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>9c68ef31-5883-4832-9156-3b2995dbdc51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>324cd7a9-7935-4840-812a-36174b6d7c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3')])[7]</value>
      <webElementGuid>b94895f4-4098-4a1b-b077-85b22f549fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>228be5af-d087-4c54-99ca-34920da11209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3']</value>
      <webElementGuid>9b1ef139-05fe-41c3-a968-fa2c1fe99fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
