<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1</name>
   <tag></tag>
   <elementGuidId>435c6a73-a0a3-4d2f-ae75-fe3e8080fe6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8a45f028-7308-4817-ac36-cdea153b8004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>b4ceb81b-d704-43fe-ac6f-354bf580595b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>68e37fe4-5178-4695-b4c0-1e37d329ca7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>92fd3b36-5658-4df0-be05-c20271109d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>9a60ff04-a3e7-4938-95af-c93ac3b83228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>cb3977d3-eaa7-411d-821f-396b23896abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[3]</value>
      <webElementGuid>eea27844-2930-4bf4-9b2e-531c0dd1d7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>48bf9793-4d71-464f-bae4-0952ec77f278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>455c7604-20ea-43b4-8884-4cac9695e1e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
