<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1_2</name>
   <tag></tag>
   <elementGuidId>887955f4-4100-4a5f-8e92-8ba41cf8c69a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>422f68e7-f242-4b89-b94e-b5692e000904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>bf377f5d-6e0b-4534-a0a5-67d5ce9abecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>2ea5e579-0e9a-4a4a-9def-de62f90e855b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>e330f2e1-3c87-4cce-b572-45385a265a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>09543958-338e-4756-ba29-f61955c7d7ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>6d76afff-a1de-461a-9793-06e884fd17d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[7]</value>
      <webElementGuid>8df7d1bb-4166-413e-b0f0-fd4aa92d9f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>f051f9e3-eb1e-4ec1-a85c-4ab89b93049b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>979e600d-8f41-4c84-9da4-053230b5ecab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
