<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>beb50221-1844-4826-bd3a-be7e61f91ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>26914ad5-fd5e-4fc7-acee-e74ffb26a55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>df16aff4-8a0d-41b2-b1c7-ab89ba1d29a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3</value>
      <webElementGuid>068141ae-73bd-41d2-adc5-62c1fbcdf8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>bdf5ba36-504c-45ef-ba97-2e0dc3dc327b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>f4d47c62-1187-4635-a8a2-655b36c5921d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>12401a6f-8390-4a73-9f18-3dcd67247a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3')])[10]</value>
      <webElementGuid>0c1ce2ea-9055-4e8d-8dfc-18669fc1d1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>ea96cf2a-c20c-48aa-9d77-c159449b7484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3']</value>
      <webElementGuid>40e84a85-b9c6-4be2-a070-ffb2db2eb642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
