<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3_1_2_3</name>
   <tag></tag>
   <elementGuidId>eba9b5dd-1820-4dc1-b3c1-130393a51eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f4383465-e2e1-4f2b-8011-335671819e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>2c9d8a41-c563-476b-b092-c75bef9260c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>d93c8987-ec76-4fb7-b427-3ea34601214b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>c66879c6-5edd-4ec7-a58b-73c6ff075371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>ded75c72-91a0-4784-a658-de499cb9d860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>3bafbe27-83c3-44f1-9733-f9eddb7986c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')]</value>
      <webElementGuid>9dd78205-a1e4-4824-be04-e20def2a2880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>14c74d59-6379-41f1-9bf4-61bdb874c4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6s2m0Dp-hzeKtIO_RHWwGcCxgGdWaTzTgWjVKPRAlneNp1QVtyLBwJRcNQc5X84GbrGRytkQaItGLWU5g7poJmuBAiV6Oba1GjVdn-kE8RsDvMa0DuKRDkTG2M6uIeurKCDWXr7UHovDvlOP9vCPVbiIUkG1NNZGaxCyd6NG8N1VomR0pxdrSUA0ByoNxyZmRNFj_htdv3wu1tECryyeyOAT5l88pwmiJqazwQpidj9uTDMSw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>091ecb31-c3e6-45d2-9d4a-3302bc79f091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
