<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12</name>
   <tag></tag>
   <elementGuidId>6201af79-a855-464c-82f2-983f59758324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2dab162d-1186-456a-a592-725992b06a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>5da3d346-8245-435d-ad1a-2411c5c96d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3</value>
      <webElementGuid>e516b4a3-203e-4f69-a35a-13bc1dd51778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>0255b715-3e19-4db9-b4c0-6f1fdaeca3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>3602f237-5c2f-4ab9-81c0-c431e69e15a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>37bff04c-9bd3-4043-bb46-1c218947e356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3')])[6]</value>
      <webElementGuid>589f4ac3-9689-47b4-b70e-cbc58d085593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>1d6909f6-b8be-4a8d-92d8-3887fbbf48e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3']</value>
      <webElementGuid>eae1e3ba-48e8-4cbf-9301-29167a4f3cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
