<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26</name>
   <tag></tag>
   <elementGuidId>e2cbaef8-c511-4dd3-a59e-b73b7d715f7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>382f418f-f595-4caf-bd3c-11d60ae81225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>bde8d227-18f0-426c-a8a5-e7ce0174167e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18</value>
      <webElementGuid>15af7509-84eb-4f16-922c-44b1281752b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>cc5eb468-c7da-4ba0-aee6-09bec5262def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>876b95b3-ffa1-409a-993a-b298e3ce78bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[4]/div/div/img</value>
      <webElementGuid>b610c256-80f3-467d-9405-b54b66c91cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18')])[8]</value>
      <webElementGuid>65901152-ab07-4b1a-a60d-263e49b7a61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/div/img</value>
      <webElementGuid>6b95943f-3e71-4a53-92b0-82f2fd04f046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4KA5y4grQMCJllk_AwDxPOty23VQ_lp80HY7RuSWf95boeknyuAlycXgaJxBvFJnXWFlKQQiVZZyEysFPsCbNCuJZZJdAfjif07yQWUAMkg8x9Ex48i3JjlRwwYib6O53SIAD5HQIOicNknYEM5BdO6M91Bsosy0tDTmVF5oRVZn7w7QWSWirJnkmopmRLPZMGaDEwlBu8DaTFHf3cTmgAwSyn1GVlx0V4rqMcwwp7Z5fozvw&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=b4364c63bfec4b18']</value>
      <webElementGuid>aabafddd-787d-49c1-a1f4-054bc7c0a747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
