<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14</name>
   <tag></tag>
   <elementGuidId>0016a125-f9c2-48a5-96a1-38ed35d14e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>485c9f7d-fa2c-4077-9ec5-4ab52ae1e57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>816b0fba-d88b-447d-818c-f8b4e40a290c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3</value>
      <webElementGuid>a8edbbec-57b2-44d0-94c8-b46d46850102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>1de3f6a7-824f-45ea-86f5-af807bf0273c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>9a61cd7c-6733-444c-bad3-a5ad6bbe9872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>82bb0f7e-33bf-4716-bbbe-c092725b68dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3')])[3]</value>
      <webElementGuid>94f3219c-01a0-4199-808c-be130630f7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>c732a8cc-136b-41fc-9e55-54624c0e3cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5D5I60HR09-uQmgyKCGtXQNo8prtj5K0mgyE-EjOJOWuEdJCyjKXZiHWUSvAAj3_TFGHKVQOZhxOZbBU78VxSDu6VCJeEt2oygO9yNpa-ew62PdxdQPISU_BhNdaCV-nU880UYWUQBbzpxIiw-KyunOdNfzpEgCjaMdHb-_df5cfDEXJy6wFDXJYmZLJtajatsJWltLTYFjCd1HC7buzl-d1bEMmw87gVkqnrRwlMG3TDZqPc&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2540becad8e998c3']</value>
      <webElementGuid>3155d62c-e1e0-4a45-b188-ea84e4805e20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
