<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>42fc4d93-76f2-420b-82e6-7c41111644d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a7e6b9be-fc43-422b-b395-464cf266d4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>f871c915-e2d5-417e-abfb-422c0ed49694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>8f4b82fe-9a29-4eb9-8b32-753c2999e469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>ecffe389-779a-48b8-a138-d904d5782085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>e93d20a0-71af-443f-883f-5e9268af6389</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      <webElementGuid>a6328b83-f9f7-40f7-8c63-6c2a7be1f82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[14]</value>
      <webElementGuid>cfddd0ff-fbfa-4584-b3db-0b5b5a29fbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/img</value>
      <webElementGuid>5829fe7c-9152-41f6-874f-2f8e3a6250aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>93014c69-426a-4f84-8002-6a623215c43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
