<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19</name>
   <tag></tag>
   <elementGuidId>99f37992-0e68-4edc-8b5c-8d2b790d5a40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0551bb9a-a58a-4084-8cc5-98253ef1ec40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>aff63a02-d7b9-4057-a67a-a5f18e63bb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56</value>
      <webElementGuid>bcd274e4-a114-459f-88b3-cf1414b06c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>5b6e6466-7fa6-4565-ba6b-ee93cc23858a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>3fd73cae-0bd9-48d3-88fe-bc116ddea495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>9b8fbcb8-30cc-4bf7-bd9c-4f2680bffb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56')])[11]</value>
      <webElementGuid>e69cc369-4dbd-46e9-91d7-73d2557bb9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>adfb4877-28bf-4949-b3e6-4d731d0f9435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7v3FYfB-GyjJZ3-_D72h5VU5nBkMJiucuY9z-Ed12TlDI9su8QAXP7Vj9OjZzSmroW27hiipm-G4ZN30g7vFeKmqRc2A83OltpEvxLQT48IQDUyDAosuWwJ8NZQ6YcE6UNHPgzjRnADicWaRapPNHmhrr2JkAAYYcHHXrzfprCMMZ3sURTbwmvUvxQYOmj4MSUidrz6U44OFkBciMnAnBYwGAxvHk_V3ECNBjL1OOj0sbyBDM&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;id=2ca57d9651816e56']</value>
      <webElementGuid>d669c7f4-7d7f-4650-90c6-2ac90aeb2bff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
