<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>b9a6c113-b98e-433f-a26e-2b79f8f56aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9737fe8d-3e5e-4324-ad6e-60b00929a3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>6410b42e-8a2c-410a-8f53-6dce1a7a5c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>53dcae83-93c8-4a3d-9fc1-ad49bc9c32cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>d93fad69-76c6-457a-84c3-3c8a36631ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.comsearchqcrugentsca_e_544995/iframe_html1body1div2div4iframe1_c-r4idlrqz2r0c</value>
      <webElementGuid>83c12c32-7979-4856-a454-8c6d01005fc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      <webElementGuid>14302372-a11a-4a7d-97ca-f62f0f83a9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[13]</value>
      <webElementGuid>8290b7c3-fafc-406e-9fea-e939f3f4a4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/img</value>
      <webElementGuid>6cd1aa1f-b0e1-4b75-a428-2c60208d6bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6uH8nV7mDOD_RPpv-RZMQ3ctmZzHEhIWx48lGPNVb7DclN4ZB3tG-9AN25tlGog12SLxgN19oFNrIIICxrXr8YvxU5JN4mueXlQzY7Q7VWanqxIZRZQ8chT7phkbsqdzwD7Em2y2Kj6PIzG3Nn299xCnGZkN7X5Y-WxP67VJKY35Ts8LfeqhqmJ_R12A8nXfuYyRgZAPekZ-ZP8eneA4yzdUDj8q_HW-WPwFMONu3O877qKRE&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>d3dc51fa-5c90-4cbb-85bc-8352e6d10840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
