<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password___container1--Grid-wrapperfor-_78970e</name>
   <tag></tag>
   <elementGuidId>b2ceb8b7-c19e-413d-8fb6-3fd1f684e60d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__container1--Grid-wrapperfor-__input2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__container1--Grid-wrapperfor-__input2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__container1--Grid-wrapperfor-__input2&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92d04c21-9d62-42fe-94dc-eb365d0557ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__container1--Grid-wrapperfor-__input2</value>
      <webElementGuid>c8425148-c5da-4727-8890-6c0b8d582047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sapUiRespGridSpanXL10 sapUiRespGridSpanL10 sapUiRespGridSpanM10 sapUiRespGridSpanS12</value>
      <webElementGuid>bc393a65-8bb5-42a8-8fac-15bcca614a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__container1--Grid-wrapperfor-__input2&quot;)</value>
      <webElementGuid>35d86f9c-af45-4cb2-969a-a32d5c29a833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__container1--Grid-wrapperfor-__input2']</value>
      <webElementGuid>1eca9068-2ede-4214-ab9b-455999fc08a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__container1--Grid']/div[4]</value>
      <webElementGuid>9fae9fbe-54a2-4181-b1d2-df616593c2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[1]</value>
      <webElementGuid>ac803274-439f-473e-b30e-4e5d5fd5fd8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/following::div[6]</value>
      <webElementGuid>880703d5-849b-4875-8702-382fd8b42a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[4]</value>
      <webElementGuid>e9621509-d30d-421e-ab48-ca1c42e0fa44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show version information.'])[2]/preceding::div[6]</value>
      <webElementGuid>619beb3c-b78b-4a4d-94a1-dd6115cccce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]</value>
      <webElementGuid>b7828336-d935-4939-81fa-8cec7fdc2f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '__container1--Grid-wrapperfor-__input2']</value>
      <webElementGuid>d7564890-4791-4f1a-a180-29d8ea6ca35d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
